module.exports = ['It is a beautiful day in Chicago today.','Temperatures expected to reach the upper 70s.',
'Right now, 75 at the lakefront, 74 at Midway, 73 at O’Hare.',
'And now, up in the sky…',
'FERRIS BUELLER’S DAY OFF',
'Don Nelson with Skyview Traffic!',
'Ferris? Ferris?',
'Thanks. Right now, we’ve got scores of accidents…',
'Tom!',
'What’s the matter?',
'Oh, it’s Ferris.',
'What? What’s wrong?',
'What’s wrong?! For Christ’s sake look at him, honey!',
'Ferris?',
'He doesn’t have a fever, but he says his stomach hurts, and he’s seeing spots.',
'What’s the matter, Ferris?',
'Papa?',
'Honey, feel his hands. They’re cold and clammy.',
'Hmm.',
'I’m fine.',
'I can get up.',
'No!\nNo.',
'I have a test today.',
'No. You—uh!',
'I have to take it.',
'I—I want to go to a good college, so I can have a fruitful life.',
'Honey, you’re not going to school like this, now.',
'Oh, fine. What’s this? What’s his problem?',
'He doesn’t feel well.',
'Yeah, right.',
'Dry that one out, you can fertilize the lawn.',
'Jeanie? Is that you?',
'Jeanie? I can’t see that far.',
'Jeanie…? Jeanie, I…',
'Bite the big one, Junior.',
'Thank you, Jeanie. You get to school.',
'Wait—You’re letting him stay home?',
'I can’t believe this. If I was bleeding out my eyes, you guys would make me go to school. This is so unfair.',
'Jeanie, please don’t be upset with me.',
'You have your health. Be thankful.',
'Oh…!',
'Oh…\nOh…',
'That’s it. I want out of this family.',
'I’m okay. I’ll just sleep.',
'Maybe I’ll have an aspirin around noon.',
'Now, listen. I’m showing some houses to that… that family from Vermont today. So I’ll be in the area.',
'Now, my office will know just where I am if you need me, okay?',
'Okay.',
'Okay…',
'I’ll check on you too, pal.',
'It’s—It’s nice to know—that I have such loving, caring parents.',
'You’re both—very special people.',
'Now, you—you get better, pumpkin.',
'Okay, pumpkin…',
'I’ll be home at six sharp.',
'If you need anything: call.',
'Ringy-dingy… Heh hee…',
'We love you, sweetie.',
'I love you too…',
'Um, muh, mee mee mee…',
'Call if you need us.',
'written and directed by JOHN HUGHES',
'They bought it.',
'Incredible.',
'One of the worst performances of my career, and they never doubted it for a second.',
'How could I possibly be expected to handle school on a day like this?',
'This is my ninth sick day this semester.',
'It’s getting pretty tough comin’ up with new illnesses.',
'If I go for ten, I’m probably gonna have to barf up a lung.',
'So I better make this one count.',
'The key to faking out the parents is the clammy hands.',
'It’s a good non-specific symptom. I’m a big believer in it.',
'Lot of people will tell you that a good phony fever is a dead lock.',
'But, uh… You get a nervous mother, you could wind up in a doctor’s office.',
'That’s worse than school.',
'You fake a stomach cramp, and when you’re bent over, moaning and wailing, you lick your palms.',
'It’s a little childish and stupid, but then, so is high school.',
'Life moves pretty fast.',
'If you don’t stop and look around once in a while, you could miss it.',
'I do have a test today. That wasn’t bullshit.',
'It’s on European socialism. I mean, really, what’s the point?',
'I’m not European. I don’t plan on being European.',
'So, who gives a crap if they’re socialists?',
'They could be fascist anarchists.',
'It still wouldn’t change the fact that I don’t own a car.',
'I recall… Central Park in fall… How you tore your dress… What a mess… I confess… 🎼',
'It’s not that I condone fascism, or any ism for that matter.',
'Isms, in my opinion, are not good.',
'A person should not believe in an ism, he should believe in himself.',
'I quote John Lennon: “I don’t believe in Beatles, I just believe in me.”',
'A good point there. After all, he was “The Walrus”.',
'I could be “The Walrus”. I’d still have to bum rides off of people.',
'Adams…?',
'Here…',
'Adamley…?',
'Here…!',
'Adamowsky…?',
'Adamson…?',
'Here.',
'Adler…?',
'…Here.',
'Anderson…? Anderson…?',
'Here!',
'Bueller…? Bueller…? Bueller…? Bueller…?',
'Um. He’s sick.',
'My best friend’s sister’s boyfriend’s brother’s girlfriend heard from this guy, who knows this kid, who’s going with a girl, who saw Ferris pass out at Thirty-One Flavors last night.',
'I guess it’s pretty serious.',
'Thank you, Simone.',
'No problem whatsoever.',
'Frye…? Frye…? Frye…?',
'Hello?',
'Cameron, babe, what’s happening?',
'Very little.',
'How do you feel?',
'Shredded.',
'Is your mother in the room?',
'She’s in Decatur. Unfortunately, she’s not staying.',
'Where are you?',
'I’m taking the day off. Now get dressed and come on over.',
'I can’t, stupid, I’m sick.',
'That’s all in your head. Come on over.',
'I feel like complete shit, Ferris. I can’t go anywhere.',
'I’m sorry to hear that. Now come on over here and pick me up!',
'Sheesh…',
'I’m dying.',
'You’re not dying. You just can’t think of anything good to do.',
'If anybody needs a day off, it’s Cameron.',
'He has a lot of things to sort out before he graduates.',
'He can’t be wound up this tight and go to college. His roommate’ll kill him.',
'When Cameron was in Egypt’s land… Let my Cameron go. 🎼',
'Pardon my French, but Cameron is so tight that if you stuck a lump of coal up his ass, in two weeks you’d have a diamond.',
'Katie Bueller.',
'This is Edward R. Rooney, Dean of Students.',
'Oh, my God. Oh, I’m so sorry.',
'I—I just completely forgot to call.',
'Then you are aware that your son is not in school today?',
'Yes, I am. Ferris is home, sick.',
'Now, I had a meeting first thing this morning.',
'I know I should have called, but it just completely slipped my mind.',
'I’m really very sorry.',
'Are you also aware, Mrs. Bueller, that Ferris does not have what we consider to be an exemplary attendance record?',
'I—I don’t understand.',
'He has missed an unacceptable number of school days.',
'In the opinion of this educator, Ferris is not taking his academic growth seriously.',
'Now, I’ve spent my morning examining his records.',
'If Ferris thinks that he can just coast through this month and still graduate, he is sorely mistaken.',
'I have no reservation whatsoever about holding him back another year. Hah hah hah…',
'This is all news to me.',
'Usually is.',
'So far this semester, he has been absent… nine times.',
'Nine times?',
'Nine times.',
'I don’t remember him being sick nine times.',
'That’s probably because he wasn’t sick. He was skipping school.',
'Wake up and smell the coffee, Mrs. Bueller.',
'It’s a fool’s paradise.',
'He is just leading you down the primrose path.',
'I can’t believe it.',
'I’ve got it right here in front of me.',
'He has missed nine days.',
'I asked for a car, I got a computer.',
'How’s that for being born under a bad sign?',
'Grace?',
'Grace!',
'Look, I can give you every assurance, Mr. Rooney, that Ferris is home, and he is very ill.',
'In fact, I debated whether or not I should even leave him.',
'Grace!!',
'I can appreciate how this time of year children are prone to taking the day off.',
'However, in Ferris’ case, I can assure you, he is truly a very sick boy.',
'Never had one lesson.',
'In 1930, the Republican-controlled House of Representatives, in an effort to alleviate the effects of the… Anyone? Anyone?',
'Great Depression… passed the… Anyone? Anyone?',
'The tariff bill… the Hawley–Smoot Tariff Act, which… Anyone? Raised or lowered?',
'Raised… tariffs, in an effort to collect more revenue for the federal government.',
'Did it work? Anyone? Anyone know the effects?',
'It did not work, and the United States sank deeper into the Great Depression.',
'Today, we have a similar debate over this. Anyone know what this is? Class? Anyone?',
'Anyone? Anyone seen this before?',
'The Laffer Curve. Anyone know what this says?',
'It says, that at this point… on the revenue curve… you will get exactly the same amount of revenue… as at this point.',
'This is very controversial. Does anyone know what Vice President Bush called this in 1980? Anyone?',
'Something—D-O-O economics.',
'Voodoo economics.',
'Jeanie.',
'I’m really sorry about your brother.',
'What are you sorry for? I have to live with the trouser snake.',
'No, I mean, I heard he’s really sick.',
'Whoa. Whoa. Who said he’s sick?',
'Whole bunch of people. They said he’s like on the verge of death.',
'And this guy in my biology class said that if Ferris dies, he’s giving his eyes to Stevie Wonder.',
'Oh, he’s such a sweetie. Gotta go.',
'Hi, Jeanie.',
'Shut up.',
'Please, do not yank my cord on this. How desperate is the situation?',
'Well, did you see “Alien”?',
'When that, uh, creature was in that guy’s stomach?',
'It kind of feels like that.',
'Freshmen.',
'Goddamn, are you kidding?',
'No, of course I’m not kidding. Do I sound like I’m kidding?',
'Who’s he talking to?',
'Ferris Bueller, do you know him?',
'Yeah. He’s getting me out of summer school.',
'We appreciate you letting us know how you’re doing.',
'We’ve got to buzz. Keep a good thought, dude.',
'Thanks.',
'Shit. I hope he doesn’t die. I can’t handle summer school.',
'Wait a minute, give me somebody else.',
'Yeah, sure, hold on.',
'You see “Alien”?',
'Yeah, why?',
'Hello?',
'Hi.',
'Hi, Ferris, how’s your bod?',
'Oh, my God, you’re dying?',
'Uh, oh.',
'Is it serious?',
'Uh, I don’t know. I hope not.',
'Think I may need a kidney transplant.',
'Shit.',
'Are you upset?',
'Excuse me.',
'Think you’ll be alive this weekend?',
'Yeah, I’d say I will.',
'Great. Maybe I’ll see you. Bye.',
'I don’t trust this kid any further than I can throw him.',
'Well, with your bad knee, Ed, you shouldn’t throw anybody.',
'It’s true.',
'What is so dangerous about a character like Ferris Bueller is he gives good kids bad ideas.',
'Uh-huh.',
'Last thing I need at this point in my career is fifteen hundred Ferris Bueller disciples running around these halls.',
'He jeopardizes my ability to effectively govern this student body.',
'Well—! Makes you look like an ass is what he does, Ed.',
'Thank you, Grace. I think you’re wrong.',
'Oh, well, he’s very popular, Ed.',
'The sportos and motorheads, geeks, sluts, bloods, waste-oids, dweebies, dickheads… they all adore him.',
'They think he’s a righteous dude.',
'That is why I have got to catch him this time.',
'To show these kids that the example he sets is a first-class ticket to nowhere.',
'Oh, Ed… You sounded like Dirty Harry just then.',
'Really?',
'Uh-huh.',
'Thanks, Grace.',
'I’m serious, man, this is ridiculous, making me wait around the house for you!',
'Why can’t you let me rot in peace?',
'Cameron, this is my ninth sick day.',
'If I get caught, I won’t graduate.',
'I’m not doing this for me, I’m doing it for you.',
'Do you know what my diastolic is?',
'Be a man.',
'Take some Pepto-Bismol, get dressed, and come on over here. I’m tired of this stuff.',
'Oh, shut up.',
'Hold—Hold—Hold your water for a second, I got another call.',
'Hello…?',
'Ferris?',
'Uh—Hi.',
'You sound terrible.',
'Really? Darn. I thought I was improving.',
'Were you sleeping?',
'Dad, can you hang on for a second?',
'Sure, pal.',
'Hang on.',
'Cameron, it’s my dad.',
'Oh, great. Keep me out of it.',
'If you’re not over here in fifteen minutes, you can find a new best friend.',
'Heh. You’ve been saying that since the fifth grade.',
'Dad?',
'Yeah?',
'All this talking has made me kind of light-headed.',
'I think I ought to lie down.',
'Take a hot bath and then wrap a hot towel around your head.',
'Wrap a hot towel around my head?',
'And then… make yourself some soup. Get a nap. Okay?',
'Okay.',
'Hey, Ferris?',
'Yep?',
'Love you, pal.',
'I love you, too.',
'I’m so disappointed in Cameron.',
'Twenty bucks says he’s sitting in his car, debating about whether or not he should go out.',
'He’ll keep calling me. He’ll keep calling me until I come over.',
'He’ll make me feel guilty…',
'This—uh! This is ridiculous.',
'Okay, I’ll go, I’ll go, I’ll go, I’ll go. What. I’ll go.',
'Shit.',
'Goddamn it!',
'Forget it. That’s it.',
'I’m not goin’…',
'I’m not goin’…!',
'In… what… way… does the author’s… use… of the… prison… symbolize…',
'The protagonist’s… struggle? And… how does this relate… to our discussion of the uses of irony?',
'Uh, Mr. Knowlan. May I interrupt, please?',
'Uh, Sloane Peterson?',
'May I have a word with you, dear?',
'My dear, I’m afraid that I’m the bearer of bad tidings.',
'Your father called.',
'Your grandmother has just passed.',
'Wha… No…',
'Oh, darlin’… Oh, honey… Oh…',
'Dead grandmother?',
'Yes, that’s what Mr. Peterson said.',
'I had Florence Sparrow notify Sloane. Poor little lamb.',
'Who’s this girl going out with?',
'It’s so hard to tell these days.',
'I do see her with Ferris Bueller quite a little bit.',
'Would you get me Mr. Peterson’s daytime number, please?',
'Sure.',
'Ed Rooney’s office.',
'This is George Peterson.',
'Oh! Ah, please hold.',
'What do you know? It’s Mr. Peterson.',
'You still want his daytime number?',
'Oh…',
'Ed Rooney.',
'Ed. This is George Peterson.',
'How are you today, sir?',
'Well, we’ve had a bit of bad luck this morning, as you may have heard.',
'Yeah, I heard, and… oh, I’m all broken up. Boy, what a blow.',
'Yeah. Yeah.',
'Well, uh, it’s been a tough morning, and, uh, we’ve got a lot of family business to take care of, so, if you wouldn’t mind excusing Sloane, I’d, uh, appreciate it.',
'Well, uh—Sure, you know, I’d be happy to.',
'Yeah, you, uh, you—you just produce a corpse, and, uh… I’ll release Sloane.',
'I wanna see this dead grandmother firsthand.',
'Ed?',
'It’s all right, Grace. It’s Ferris Bueller, the little twerp.',
'I’m gonna set the trap and let him fall right into it.',
'Ooo…',
'Uh, uh, Ed, I—I’m sorry, did you say you wanted to see a body?',
'Yeah, that’s right.',
'Just, uh, roll her old bones on over here, and I’ll dig up your daughter.',
'You know, that’s school policy.',
'Oh?',
'Uh, was this your mother?',
'Uh… No, my wife’s mother.',
'Ed Rooney’s office.',
'Hi, this is Ferris Bueller, can I speak to Mr. Rooney, please?',
'Thank you.',
'Ah… Hold.',
'Tell you what, dipshit. You don’t like my policies, you can just come on down here and smooch my big-old white butt.',
'Ed.',
'Pucker up, buttercup. (What?)',
'Ferris Bueller’s on line two.',
'Hey, Mr. Rooney, how you doing?',
'Listen, uh, I’m sorry to disturb you at work, but I’m not feeling very well today, and I was wondering if it might be possible for my sister to bring home any assignments from my classes that I might need.',
'Have a nice day.',
'Ahem… Mr. Peterson?',
'Ahem!',
'Um… You know, I—I—I think I owe you an apology, sir.',
'Well, I should say you do.',
'I… uh… I, I, I…',
'Well, I think you should be sorry, for Christ’s sake.',
'A family member dies, and you insult me. What the hell is the matter with you anyway?',
'Uh—Uh—Uh… Well… I… er…',
'I—I—I really don’t know, sir.',
'I mean, I—I didn’t think I was talking to you. I thought I was talking to somebody else.',
'You know, sir, that I would never deliberately insult you like that.',
'I… I… I—just—I can’t—begin to tell you how embarrassed I am.',
'(What do you want?)',
'Pardon my French, but you’re an asshole!',
'(Ed, what do you want?)',
'Asshole!',
'Uh, you’re—absolutely right, sir. You’ve hit the nail right on the head.',
'(Find out where she is!)',
'This isn’t over yet, buster. Do you read me?',
'Uh, loud and clear, Mr. Peterson.',
'Call me “sir”, goddamn it!',
'Yes, yes, yes, sir, yes, sir.',
'That’s better.',
'And you just mind your p’s and q’s, buster. And remember who you’re dealing with.',
'Bueller. Ferris Bueller.',
'Now, I’m—I’m a little scared ‘cause what if he recognizes my voice?',
'(Impossible. You’re doing great.)',
'Yeah?',
'She’s in—wait…!',
'Rooney!',
'Oh… Oh…',
'Rooney. Calm down!',
'Uh, just a moment… Uh… Uh…',
'(Ed! Get in here!)',
'Ah… just a… just a little… office difficulty, sir.',
'Rooney, I don’t have all day to bark at you, so I’m gonna make this short and sweet.',
'(It’s great. Perfect. I love it.)',
'I want my daughter out in front of the school in ten minutes by herself. I don’t want anybody—',
'(What?)',
'(It’s too suspicious. He’ll think something’s up. Cover it.)',
'(You.)',
'(Talk.)',
'(You!)',
'(Talk!)',
'(Come on…)',
'(Talk. Now.)',
'Rooney! Ahem. Rooney.',
'Yes, sir. Yes.',
'Listen here, pay attention. I changed my mind!',
'I want you out in front of the school with her! I’d like to have a few words with you, by God!',
'On second thought, we don’t have time to talk right now! We’ll get together soon, and we’ll have lunch!',
'(Ow!)',
'What the hell is wrong with you?',
'Wait. Wait!',
'Where’s your brain?!',
'Why’d you kick me?!',
'Where’s your brain?',
'Why’d you kick me?',
'Where’s your brain…?',
'I asked you first.',
'How can we pick up Sloane if Rooney is there with her?',
'Uh. I said for her to be there alone, and you freaked.',
'Now, I didn’t—I didn’t hit you. I lightly slapped you.',
'You… hit me.',
'Look, don’t ask me to participate in your stupid crap if you don’t like the way I do it.',
'You make me get out of bed. You make me come over here.',
'You make me make a phony phone call to Edward Rooney?',
'The man could squash my nuts into oblivion.',
'And—And—And—And then, and then, you deliberately hurt my feelings.',
'No, no. I did not deliberately—I didn’t deliberately hurt your feelings.',
'Oh, really?',
'Really, no. No, I didn’t.',
'What are you doin’?',
'See you later, pal, I’m going home.',
'Oh, no, no, come on, don’t do that.',
'Have a nice life.',
'Ah, Cameron, wait a minute. Cameron, come back.',
'I didn’t mean to lose my temper.',
'I’m sorry. It was uncalled for.',
'You serious?',
'Yeah.',
'Here you go.',
'Thank you.',
'You did screw up, though, right?',
'I mean… not that it was completely your fault.',
'Why?',
'Well… to fix the situation… I’m gonna have to ask you for a small favor.',
'The 1961 Ferrari 250 GT California.',
'Less than a hundred were made.',
'My father spent three years restoring this car.',
'It is his love, it is his passion…',
'It is his fault he didn’t lock the garage.',
'Ferris, what are you talking about?',
'Oo!',
'Ferris, my father loves this car more than life itself.',
'A man with priorities so far out of whack doesn’t deserve such a fine automobile.',
'No. No.',
'Apparently you don’t understand.',
'Wow.',
'Ferris, he never drives it. He just rubs it with a diaper.',
'Hey, remember how insane he went when I broke my retainer?',
'Huh?',
'Come on, that was a little piece of plastic, this is a Ferrari.',
'Qué bella.',
'Cameron, I’m sorry. But we can’t pick up Sloane in your car.',
'Mr. Rooney would never believe Mr. Peterson drives that piece of shit.',
'Not a piece of shit.',
'It is a piece of shit.',
'Don’t worry about it, I don’t even have a piece of shit, I have to envy yours.',
'Oh, thanks.',
'Look, I’m sorry. There’s nothing else we can do.',
'He knows the mileage, Ferris.',
'He doesn’t trust you?',
'Never has, never will.',
'Look, this is real simple.',
'Whatever miles we put on, we’ll take off.',
'How?',
'We’ll drive home backwards.',
'Huh! No.',
'No!',
'Ferris, forget it. You’re just gonna have to think of something else.',
'I’m putting my foot down.',
'How about we rent a nice Cadillac? My treat!',
'We could call a limo!',
'A nice stretch-job with a TV and a bar? How about that?',
'Come on, live a little.',
'Once again, let me tell you how deeply saddened I am by your loss. I, uh…',
'I had a grandmother once.',
'Uh… Two, actually.',
'Deficits. Who will have to pay that eventually? Anyone? Anyone know?',
'“Man that is born of woman hath but a short time to live and is full of misery.',
'“He cometh up and is cut down like a flow’r.',
'“He flee’th as if it were a shadow and never continueth in one stay.”',
'Oh, dear.',
'Between grief and nothing, I’ll take grief.',
'Great.',
'Oh, Sloane, dear. Hurry along now.',
'I guess that’s my dad.',
'Yeah.',
'Gotta go.',
'Mr. Rooney. Ed.',
'You’re a beautiful man.',
'Thank you.',
'I wanna thank you for your warmth and compassion.',
'Higher… what… rates? Anyone?',
'Higher marginal rates… on your taxes. Any questions so far?',
'Shit.',
'Hi.',
'Do you have a kiss for Daddy?',
'Are you kidding?',
'So, that’s how it is in their family.',
'Hi, Cameron. You comfortable?',
'Hi, Sloane. No.',
'What are we gonna do?',
'The question isn’t: What are we going to do?',
'The question is: What aren’t we going to do?',
'Don’t say we’re not going to take the car home.',
'Please don’t say we’re not going to take the car home.',
'If you had access to a car like this, would you take it back right away?',
'Neither would I.',
'Hey, Ferris, don’t go so fast!',
'Red line, red line, red line.',
'Ferris, get out!',
'Thank you.',
'Save Ferris.',
'God loves you, you’re very generous.',
'(Thank you.)',
'Save Ferris, save Ferris.',
'Save Ferris Bueller? Save Ferris.',
'Save Ferris?',
'What?',
'Well, uh… See, we’re collecting money to buy Ferris Bueller a new kidney, and they run about fifty G’s or so, so if you could help out…',
'Go piss up a flagpole.',
'I’m sorry?',
'You should be.',
'Hey…',
'Hey! Hey…',
'What if you need a favor someday from Ferris Bueller? Then where will you be, huh?',
'You heartless wench!',
'Peterson home on line one.',
'And… watch your mouth this time.',
'Go soak your head.',
'We can’t come to the phone right now. We’ve had a… death in the family…',
'Grace, Ferris Bueller’s behind this. There is no doubt in my mind.',
'And now he’s got Sloane Peterson involved in this thing.',
'Her grandmother, too.',
'You pinhead.',
'…you need to reach us, we’ll be at the following number. Oh, oh…!',
'Okay.',
'I did not achieve this position in life by having some snot-nosed punk leave my cheese out in the wind.',
'You have reached the Coughlin Brothers Mortuary.',
'We are deeply sorry we are unable to come to the phone right now, but if you leave your name and number, we’ll get back to you as soon as is humanly possible.',
'Something’s going on, goddamn it.',
'And I’m gonna find out what it is.',
'I’m gonna catch this kid, and I’m gonna put one hell of a dent in his future.',
'Fifteen years from now, when he looks back on the ruin his life’s become, he is going to remember Edward Rooney.',
'Wrong.',
'What?',
'Not here.',
'We’re not leaving the car here.',
'Why not?',
'Because we’re not.',
'I want the car back home where it belongs, right now.',
'Come on, let’s go.',
'Cameron, what’s gonna happen to it? It’s in a garage.',
'It could get wrecked, stolen, scratched… breathed on wrong—a pigeon could shit on it. Who knows?',
'Listen, will you calm down, please?',
'I’m gonna give the guy a fiver to watch it.',
'What guy?',
'Hey, how you doin’?',
'D’you speak English?',
'Uh, what country do you think this is?',
'Okay. Listen. Uh, I want you to take extra special care of this vehicle. Okay?',
'Hey, no problem.',
'Great.',
'Trust me.',
'Sir.',
'Come on. Come.',
'Relax.',
'Ha.',
'Uh, you fellows have nothin’ to worry about. I’m a professional.',
'Professional what?',
'See what a finski can do to a guy’s attitude?',
'Cameron, come on.',
'Come on, come on.',
'Paper?',
'Hey, look at that.',
'Go! Go!',
'Oh, bless his little heart.',
'(Nine times.)',
'Ferris, you think the car’s all right?',
'Sure.',
'This is the world’s tallest building.',
'Ferris, I don’t feel too good. Can we leave soon?',
'Here, climb up on this.',
'Come on, everybody.',
'Cameron.',
'Okay, now. Lean forward against the glass like this.',
'Oh, my God.',
'Isn’t that great?',
'The city looks so peaceful from up here.',
'Anything is peaceful from one thousand, three hundred and fifty-three feet.',
'I think I see my dad.',
'We got a lot to do, let’s go.',
'Shit.',
'Son of a bitch is down there somewhere.',
'You want to get married?',
'Sure.',
'Today?',
'I’m serious.',
'I—I’m not getting married.',
'Why not?',
'What do you mean, “Why not?” Think about it.',
'Well, no—besides being too young, having no place to live, you feeling a little awkward about being the only cheerleader with a husband…',
'Give me one good reason why not.',
'I’ll give you two good reasons why not: my mother and my father.',
'They’re married and they hate each other. You’ve seen ‘em. Am I right?',
'So what?',
'Well, it’s like that car.',
'He loves the car. He hates his wife.',
'Thank you.',
'Can we please get the hell out of here?',
'This place gives me the creeps.',
'Why didn’t you tell me we were coming to a—',
'Hello, may I help you?',
'You can sure as hell try.',
'Hi. I’m Abe Froman. Party of three for twelve.',
'Is there a problem?',
'You are Abe Froman?',
'That’s right. I’m Abe Froman.',
'The “Sausage King of Chicago”?',
'Yeah. That’s me.',
'Listen, young man, entre nous, I’m very busy here.',
'Why don’t you take the kids and go back to the clubhouse?',
'Are you suggesting that I’m not who I say I am?',
'I’m suggesting that you leave before I have to get snooty.',
'Snooty?',
'Snotty.',
'Snotty?',
'Okay, “Abe”. Let’s go.',
'No, I’m not going anywhere. No. We’d like to be seated.',
'Listen, young man, either you take the field trip outside, or I’m going to have to call… the police.',
'The poli… You’re gonna call the police on me?',
'Yes.',
'Fine. As a matter of fact, I’ll call ‘em myself.',
'Yes. Call the police.',
'Ha. This’ll be a hoot.',
'Here, give me the phone. I have another call.',
'No.',
'I’ve had enough of this horsing around. Give me the phone back.',
'You touch me, I yell, “Rat”.',
'There’s another phone around here somewhere. Find it.',
'Wonderful.',
'I weep for the future.',
'Okay, Ferris, can we just let it go, please?',
'Ferris, please. You’ve gone too far. You’re gonna get busted!',
'A: You can never go too far. B: If I’m gonna get busted, it is not gonna be by a guy like that.',
'Come on. “Abe”.',
'Ask for Abe Froman.',
'Chez Quis, bonjour.',
'May I speak to Abe Froman. The “Sausage King of Chicago”?',
'Abe Froman?',
'Let me check the restaurant. Could you describe him for me, please?',
'Leather jacket, white T-shirt, sweater vest.',
'He’s devastatingly handsome.',
'Hold on one moment.',
'Yes, thank you.',
'Ahem! Mr. Froman? This is Sergeant Peterson, Chicago Police.',
'I appreciate your understanding.',
'Don’t think twice.',
'It’s understanding that makes it possible for people like us to tolerate a person like yourself.',
'Thank you.',
'Don’t mention it.',
'Enjoy your lunch.',
'Darling, you were wonderful.',
'Cameron, dear friend. You thought we wouldn’t have any fun. Shame on you.',
'(Maybe I’m overreacting. Maybe Ferris isn’t such a bad guy.)',
'(After all, I got a car. He got a computer.)',
'(But still, why should he get to do whatever he wants, whenever he wants?)',
'(Why should everything work out for him?)',
'(What makes him so goddamn special?)',
'Screw ‘im.',
'I used to think that my family was the only one that had weirdness in it.',
'That used to worry me.',
'Then I saw how Cameron’s family functioned.',
'His home life is really twisted.',
'That’s why he’s sick all the time. It really bothers him.',
'He’s the only guy I know who feels better when he’s sick.',
'If I had to live in that house, I’d probably pray for disease, too.',
'The place is like a museum.',
'It’s very beautiful and very cold, and you’re not allowed to touch anything.',
'Can you appreciate what it must have been like for Cameron to be in that joint as a baby?',
'I’m actually amazed that I got the car out of the garage.',
'I caught Cameron digging the ride once or twice.',
'It’s good for him. It teaches him to deal with his fear.',
'Plus—and I must be honest here—I love driving it. It is so choice.',
'If you have the means, I highly recommend picking one up.',
'Thank you.',
'Yes, sir.',
'Mint.',
'Well, hello, Jeanie. Who’s bothering you now?',
'Is Mr. Rooney in?',
'No, I’m sorry, he’s not. Can I help you?',
'I seriously doubt it. When’s he back?',
'I… don’t know. He’s left the school grounds on personal business.',
'What’s that supposed to mean?',
'I suppose it means it’s personal, and it’s none of your business, young lady.',
'Ah… Nice attitude.',
'Isn’t Mrs. Hagel expecting you in consumer-ed class?',
'Probably.',
'What a little asshole.',
'Dave, you’ve got to consider raising your advertising budget.',
'We don’t have the money.',
'Dave, if you wanna sell, you have to spend. It’s as simple as that.',
'Four thousand restaurants in the downtown area. I pick the one my father goes to.',
'We’re pinched, for sure.',
'No way, Cameron.',
'Only the meek get pinched. The bold survive.',
'Let’s go.',
'Let’s surrender.',
'Never.',
'Dave, I know it sounds like I’m beating a dead horse on this one. But I’m telling you, that that’s not the case.',
'We don’t have the money. We don’t have the—',
'Dave, you’re one of the brightest guys in this business. You know what it takes to push this over the top.',
'We’re gonna go out heavy on TV and lighten up on the radio and the print. Okay?',
'He’s got the money!',
'Listen—Look, come on back to my office. I’ll lay out the entire—',
'He’s got the money.',
'Dave, we know you’ve got the money, we know you’ve got the money. We just have to spend it, that’s all (you bonehead).',
'(Bueller.)',
'Les jeux sont faits. Translation: The game is up.',
'Your ass is mine!',
'Runner at first base, nobody out.',
'That’s the first hit they’ve had… since the fifth inning. Only the fourth hit in the game.',
'O and two, the count.',
'There’s a drive, left field, twisting, and into foul territory.',
'Boy, I’m really surprised they didn’t go for it in that inning.',
'Lee Smith.',
'What’s the score?',
'Nothin’, nothin’.',
'Who’s winning?',
'The Bears.',
'There’s the ball, bunted foul back to the screen.',
'Boy, I don’t know…',
'Think I broke my thumb.',
'Hey… Batter, batter, batter, batter, batter! S—wing, batter.',
'Come on.',
'Hey… Batter, batter, batter, batter! S—wing, batter.',
'He can’t hit, he can’t hit, he can’t hit, he can’t hit, he can’t hit! S—wing, batter.',
'Hey, Cameron.',
'Do you realize if we played by the rules, right now we’d be in gym?',
'Heh heh heh…',
'Keep movin’, keep movin’…',
'You’re up now!',
'Come on, get the piano off that back! Let’s go!',
'Come on, boys, let’s go!',
'You’ll never get out of here—move!',
'Come on, move!',
'I hate him.',
'Who is it?',
'It’s Ed Rooney, Ferris. I’d like to have a word with you.',
'Oh. I’m sorry. I can’t come to the door right now.',
'I’m afraid that in my weakened condition, I could take a nasty spill down the stairs and subject myself to further school absences.',
'Save it, Ferris. Come down here.',
'You can reach my parents at their places of business.',
'Thank you for stopping by, heh.',
'I appreciate your concern for my well-being.',
'I am not leaving till you come down and talk to me, Ferris.',
'Have a nice day.',
'You’re in big trouble, buster. Get down here!',
'Ferris… Ferris!',
'Who is it?',
'You know goddamn well who it is!',
'Oh. I’m sorry. I can’t come to the door right now.',
'I’m afraid that in my weakened condition, I could take a nasty spill down the stairs and subject myself to further school absences.',
'You can reach my parents at their places of business.',
'Thank you for stopping by, heh.',
'I appreciate your concern for my well-being.',
'Have a nice day.',
'Ah! (Damn it.)',
'Oh, mud.',
'Oh! Oh…',
'Bueller, you son of a bitch…',
'My shoe… Oh…',
'Damn it!',
'Oh, shit.',
'Hi, doggie!',
'Stay, boy.',
'No, no. Stay.',
'Stay!',
'Sit!',
'Site! Heel! Stay!',
'And passing the reviewing stand now: Silbernen Ritter Drum and Bugle Corps.',
'The United German-American Male and Female Caucus.',
'The Empire German-Americans…',
'It’s getting late, buddy. We better go get the car back home.',
'What?',
'What do you me—We have a few hours. We have until six.',
'I’m sorry—I mean, I know you don’t care, but it does mean my ass.',
'You think I don’t care?',
'I know you don’t care.',
'Oh… Ah… Oh, that hurts, Cameron.',
'Cameron, what have you seen today?',
'Nothing good.',
'Nothing…? Noth…? Nothing g…? This…',
'What do you mean, “Nothing good”?',
'We’ve seen everything good! We’ve seen the whole city!',
'Uh uh.',
'We went to a museum, we saw priceless works of art…',
'We ate—We ate pancreas.',
'We saw—What? What’s wrong?',
'(Look over there.)',
'What’s he doing?',
'He’s licking the glass and making obscene gestures with his hands.',
'What?',
'Hee hee, ha ha…',
'Ah! Ah, ha! Don’t! Don’t! Ah, ha…',
'He didn’t leave. He’s probably doing something.',
'No, it really busts my hump, you know?',
'Oh, Cameron, he didn’t ditch us or anything. He’s here. He’s here.',
'Hey, for all we know, he went back to school.',
'He would not go back to school.',
'Yeah, he’d do it. He’d just do it just to make me sweat.',
'No, he would not. Cameron, come on.',
'Makes me mad.',
'Ladies and gentlemen, you’re such a wonderful crowd. We’d like to play a little tune for you.',
'It’s one of my personal favorites. And I’d like to dedicate it to a young man who doesn’t think he’s seen anything good today.',
'Cameron Frye, this one’s for you.',
'Danke schoen, darling, danke schoen… 🎵',
'Aaah!',
'Ferris! Get off of the float!',
'What are you doing?!',
'Thank you for all the joy and pain… 🎵',
'Get off the float! I can’t believe you!',
'How’d you get up there?!',
'You’re out of your mind!',
'Picture shows, second balcony, 🎵',
'Was the place we’d meet, second seat, go Dutch treat, you were sweet… 🎵',
'Danke schoen, darling, danke schoen… 🎵',
'Save those lies, darling don’t explain… 🎵',
'I recall Central Park in fall… 🎵',
'How you tore your dress, what a mess… 🎵',
'You know, as long as I’ve known him everything works for him.',
'There’s nothing he can’t handle. I can’t handle anything.',
'School, parents, the future…',
'Ferris can do anything.',
'I don’t know what I’m gonna do.',
'College.',
'Yeah. But to do what?',
'What are you interested in?',
'Nothing.',
'Me neither.',
'Hah!',
'Danke schoen, auf wiedersehen, danke schoen… 🎵',
'You’re crazy! Heh heh…',
'What do you think Ferris is gonna do?',
'He’s gonna be a fry cook on Venus.',
'Well, shake it up, baby, now! (Shake it up, baby!) 🎶',
'Twist and shout! (Twist and shout!) 🎶',
'Come on, come on, come on, come on, baby, now! (Come on, baby!) 🎶',
'Come on and work it on out! (Work it on out!) 🎶',
'Well, work it on out! (Work it on out!) 🎶',
'You know you look so good! (Look so good!) 🎶',
'You know you got me goin’ now! (Got me goin’!) 🎶',
'Just like I knew you would! (Like I knew you would, oo!) 🎶',
'Well, shake it up, baby, now! (Shake it up, baby!) 🎶',
'Twist and shout! (Twist and shout!) 🎶',
'Come on, come on, come on, come on, baby, now! (Come on, baby!) 🎶',
'Come on and work it on out! (Work it on out, oo!) 🎶',
'You know you twisted, little girl! (Twist little girl!) 🎶',
'You know you twist so fine! (Twist so fine!) 🎶',
'Come on and twist a little closer now! (Twist a little closer!) 🎶',
'And let me know that you’re mine! (Let me know you’re mine, oo!) 🎶',
'Yeah! Uh! Huh! Huh!',
'Ah…! Ah…! Ah…! Ah…! Wow!',
'Baby, now! (Shake it up, baby!) 🎶',
'Twist and shout! (Twist and shout!) 🎶',
'Come on, come on, come on, come on, baby, now! (Come on, baby!) 🎶',
'Come on and work it on out! (Work it on out!) 🎶',
'You know you twisted, little girl! (Twist little girl!) 🎶',
'You know you twist so fine! (Twist so fine!) 🎶',
'Come on and twist a little closer now! (Twist a little closer!) 🎶',
'And let me know that you’re mine! (Let me know you’re mine, oo!) 🎶',
'Well, shake it, shake it, shake it, baby, now! (Shake it up, baby!) 🎶',
'Well, shake it, shake it, shake it, baby, now! (Shake it up, baby!) 🎶',
'Well, shake it, shake it, shake it, baby, now! (Shake it up, baby!) 🎶',
'Ah…! Ah…! Ah…! Ah…!',
'Ch—rist.',
'Poochie, poochie, poochie.',
'Look what Uncle Ed has for you, you little fucker…',
'Jeeza…',
'Sleep tight, pooch.',
'I knew it! Oh!',
'Well, where is she?',
'Look, this is her daughter.',
'Well, do you know where she is?',
'Do you know when she’ll be back?',
'Do you know anything?',
'Ferris.',
'Bueller.',
'Ha!',
'Ya!',
'Aaahh!! Aargh!! Aaah…!',
'You’re psychotic. You are, man.',
'You’re out of your goddamn mind. I can’t believe you did that.',
'I can’t believe you went on a goddamn parade float!',
'Okay, okay, wait. No, okay, wait. Okay.',
'“Yeah, yeah. This tune is one of my personal favorites.”',
'You’re out of your mind.',
'Do you realize how many people saw you?',
'You’re nailed.',
'Nah, nah…',
'You are nailed.',
'You are!',
'Who’d believe that I was in a parade? Who the hell am I?',
'Besides, anybody who would nail me wouldn’t go to a parade.',
'My mother would.',
'I’m not worried about your mother—',
'That was so quick!',
'Hey.',
'This looks okay to me, Cameron.',
'Looks great, let’s roll!',
'Heh. Here you go. Nice job. Thank you.',
'Hey, you’re a very generous individual. Come back anytime.',
'Right, okay.',
'Thanks a lot.',
'Watch the seat.',
'Sorry.',
'Have a good night.',
'Bye, you guys!',
'Yeah, see you later!',
'Later!',
'Woo…! Ha ha ha! Yeah, babe, we got to do this again.',
'Look, this is… This is not a phony phone call!',
'There is an intruder—male, Caucasian, possibly armed, certainly weird—in… my kitchen!',
'Yeah, my, my… My name’s Bueller…!',
'Look, it’s real nice that you hope my brother’s feeling better, but I’m in danger, okay?',
'I am very cute. I am very alone. And I’m very protective of my body.',
'I do not want it violated, or killed, all right?!',
'I need help!',
'Speak any English?!',
'Dick! Head!',
'God…',
'Excuse me.',
'Whoever’s in the house is still in the house, I’d like you to know that I’ve just called the police.',
'So if you have any brains whatsoever, you’ll get your ass out of my house real quick.',
'I’d also like to add that I have my father’s gun and a scorching case of herpes.',
'Hey, wait, wait, wait! That’s my car! I’ll move it!',
'He got my keys…!',
'You shithead!',
'Aaah!! Aargh!',
'I feel pretty good.',
'Yeah…?',
'I feel real good.',
'Those guys. Those guys were nice, huh? At the garage. I was a little worried about them.',
'Turned out good.',
'Hey. Cameron?',
'Yeah?',
'How many miles did you say this thing had on it when we left?',
'A hundred an’… twenty-six and halfway between three and four tenths.',
'Why?',
'How many miles are on it now?',
'Here’s where Cameron goes berserk.',
'Aooohhhhhhhhhhhh!!!!!!!!!!!!!!!!!!',
'Cameron. Are you okay? Cam?',
'Cameron, cut that out!',
'Who is it?',
'Oh. I’m sorry. I can’t come to the door right now.',
'I’m afraid that in my weakened condition, I could take a nasty spill down the stairs and subject myself…',
'God bless the police.',
'I’m saved! Oh, thank you, God! Thank you, thank you! You are the best!',
'…Have a nice day.',
'Thank—',
'I heard that you were feeling ill… 🎼',
'Headache, fever, and a chill… 🎼',
'I came to help restore your pluck… 🎼',
'‘Cause I’m the nurse who likes to— 🎼',
'This may very well be for real.',
'I think Cameron might have blown a microchip or two.',
'He’s always been a little keyed up.',
'All I wanted to do was give him a good day.',
'We’re gonna graduate in a couple of months, and then… we’ll have the summer. He’ll work and I’ll work.',
'We’ll see each other at night and on the weekends.',
'Then he’ll go to one school, and I’ll go to another.',
'Basically that will be it.',
'Sloane’s as big a problem.',
'She still has another year of high school. How do I deal with that?',
'I was serious when I said I would marry her. I would.',
'Cameron? Cam? Can you hear me? Cameron?',
'Blink if you understand me.',
'Cameron has never been in love.',
'At least nobody’s ever been in love with him.',
'If things don’t change for him, he’s gonna marry the first girl he lays.',
'And she’s gonna treat him like shit.',
'Because she will have given him what he has built up in his mind as the end-all, be-all of human existence.',
'She won’t respect him.',
'‘Cause you can’t respect somebody who kisses your ass.',
'Just doesn’t work.',
'Ferris. We better try something else.',
'This isn’t working.',
'You feeling any better, Cameron?',
'Cam? Why don’t you come in here? It’s really nice.',
'Cameron, I can flip out real easy, too. It’s okay.',
'Sooner or later everybody goes to the zoo.',
'Maybe he’s really sick.',
'Maybe he isn’t just torturing himself.',
'Hey…! Hey, hey…! Hey, Cameron!',
'Cam! Cameron, wake up!',
'Come on, wake up. Hey, wake up.',
'Oh, shit, Cameron, come on. Cameron!',
'Come on, wake up!',
'Hey!',
'What is that?',
'Ferris Bueller, you’re my hero.',
'You’re kidding?',
'Wow, that was pretty impressive, man.',
'You bitch. Oh, you son of a bitch!',
'Come on!',
'Tarzan!',
'Sheena!',
'Drugs?',
'Thank you, no. I’m straight.',
'I meant, are you in here for drugs?',
'Why are you here?',
'Drugs.',
'I don’t know why I’m here.',
'Why don’t you go home?',
'Why don’t you put your thumb up your butt?',
'You wear too much eye makeup.',
'My sister wears too much. People think she’s a whore.',
'You don’t wanna talk about your problem?',
'With you? Are you serious?',
'I’m serious.',
'Blow yourself.',
'All right, you wanna know what’s wrong?',
'I know what’s wrong. I just wanna hear you say it.',
'In a nutshell, I hate my brother. How’s that?',
'That’s cool. Did you blow him away or something?',
'No, not yet.',
'See, I went home to confirm that the shithead was ditching school. And when I was there, a guy broke into the house. I called the cops, and they picked me up for making a phony phone call.',
'What do you care if your brother ditches school?',
'Why should he get to ditch, when everybody else has to go?',
'You could ditch.',
'Yeah. I’d get caught.',
'I see.',
'So you’re pissed off ‘cause he ditches and doesn’t get caught, is that it?',
'Basically.',
'Basically. Then your problem is you.',
'Excuse me?',
'Excuse you.',
'You ought to spend a little more time dealing with yourself, little less time worrying about what your brother does.',
'That’s just an opinion.',
'Hmm. What are you, a psychiatrist?',
'No.',
'Then why don’t you keep your opinions to yourself?',
'Somebody you should talk to.',
'If you say, “Ferris Bueller”, you lose a testicle.',
'Oh, you know him?',
'You know, that whole time I was just thinking things over.',
'I was, like… I was, like, meditating.',
'Then, I sort of watched myself from inside.',
'I realized it was ridiculous.',
'Bein’ afraid… worryin’ about everything… wishin’ I was dead… All that shit, I’m tired of it.',
'It’s the best day of my life.',
'I’m gonna miss you guys next year.',
'Cameron? Can I ask you a question?',
'Yeah.',
'Did you see me change out of my clothes by the Jacuzzi?',
'Did you? You saw me?',
'I thought you were catatonic.',
'That’s okay. I’m not embarrassed.',
'I… better check on the car.',
'Hey, Ferris!',
'Yeah?',
'Miles aren’t coming off.',
'The miles aren’t coming off going in reverse.',
'Huh. Well, I thought that might be a problem.',
'Just have to crack open the odometer, roll it back by hand.',
'No, forget it. Forget it.',
'I gotta take a stand.',
'I’m bullshit.',
'I put up with everything.',
'My old man pushes me around.',
'I never say anything!',
'Well, he’s not the problem. I’m the problem.',
'I gotta take a stand. I gotta take a stand against him.',
'I am not gonna sit on my ass as the events that affect me unfold to determine the course of my life.',
'I’m gonna take a stand. I’m gonna defend it.',
'Right or wrong, I’m gonna defend it.',
'I’m so sick of his shit!',
'I can’t stand him, and I hate this goddamn car.',
'Who do you love? Who do you love? You love a car.',
'You son of a… bitch.',
'Heh. Shit.',
'I dented the shit out of it.',
'Good.',
'My father will come home, he’ll see what I did. I can’t hide this.',
'He’ll come home, he’ll see what I did. He’ll have to deal with me.',
'I don’t care, I really don’t.',
'I’m just tired of being afraid.',
'Hell with him.',
'I can’t wait to see the look on the bastard’s face.',
'What’d I do?',
'What did I do?',
'You killed the car.',
'Whoa!',
'Holy shit!',
'Cameron, it’s my fault.',
'I’ll take the heat for it.',
'We’ll wait for your father to come home, and when he gets here, I’ll tell him that I did it.',
'He hates me anyway.',
'No. I’ll take it.',
'No, I’ll take it.',
'No. No. You don’t want this much heat.',
'I want it. If I didn’t want it, I wouldn’t have let you take the car out this morning.',
'I made you take the car this morning.',
'I could’ve stopped you.',
'It is possible to stop Mr. Ferris Bueller, you know?',
'No, I want it. I’m gonna take it. That’s it.',
'When Morris comes home, he and I’ll just have a little chat.',
'It’s cool.',
'No, it’s gonna be good.',
'Thanks anyway.',
'This is a shock to me.',
'I mean, first of all, I don’t know why she wasn’t in school.',
'And second of all, I just can’t believe she came to you with this story about an intruder.',
'Well, for whatever reason she did it. I think she’s had a pretty good scare.',
'Well. I really appreciate your calling me. Really.',
'I can assure you that her father and I are going to have a long talk with her when we get home.',
'Thank you so much.',
'Oh, by the way, I hope your son is feeling better.',
'I beg your pardon?',
'Tell him all the guys at the station here are pulling for him, hmm?',
'Oh, right.',
'Ahem.',
'Hi.',
'Don’t “hi” me, young lady.',
'I wanna get out of here now, all right?',
'Okay…',
'No, now. Let’s get out of here.',
'O—Okay.',
'Okay?',
'Yes.',
'Now.',
'Fine.',
'Okay.',
'She’s a… little hyper.',
'Yeah.',
'Uh… Uh… Let’s not ruin this with a lot of talk, all right, okay?',
'You didn’t tell me your name.',
'Oh. Well, it’s—it’s Jean, but, uh, a lot—a lot of guys call me Shauna.',
'Okay, Jean.',
'Cool, uh… That’s great, uh… Uh, I’ll see you, okay…? Yeah… Ha ha ha…!',
'Jeanie, now! Now!',
'Okay…!',
'Danke schoen… Darlin’, danke schoen…',
'I had a great time today.',
'Yeah. It was pretty cool.',
'Do—you think Cameron’s gonna be okay?',
'Oh, yeah. Yeah, sure. For the first time in his life.',
'He’s gonna be just fine.',
'You knew what you were doing when you woke up this morning, didn’t you?',
'Me? No.',
'Oh, shit. I have to go.',
'I’ll call you tonight.',
'Okay.',
'I love you!',
'I love you, too!',
'He’s gonna marry me.',
'Do you know what it’s like to be pulled out of work to pick up your daughter at the police station?',
'No, not really.',
'Well, on top of everything else, I was about to close the damn deal with the Vermont people.',
'I’m sorry.',
'I was gonna take my commission and buy Ferris a car.',
'Aah!',
'Jeanie, what the hell are you doing?! You trying to kill us?',
'God, look at this mess. Paper all over the place. I’ll never get this back in order.',
'Aaaahh!',
'Jeanie!',
'Slow down! Now! Now!',
'I can’t drive when you’re yelling at me! Stop it!',
'Hi, how you doing? Ferris Bueller.',
'Hi.',
'No, don’t get up.',
'Hey!',
'Smells delicious.',
'Dinner’s ready.',
'What? Who’s that?',
'What’s wrong?',
'Everything.',
'I just picked up Jeanie at the police station.',
'She got a speeding ticket, another speeding ticket, and I lost the Vermont deal because of her.',
'I think we should shoot her.',
'Looking for this?',
'I got you, Ferris.',
'How’s Ferris? Let’s go in and check him.',
'Okay, honey, yeah.',
'How was your day?',
'I have dreamed about this.',
'This time, goddamn, you little bastard… I’ve got you right where I want you.',
'Ferris, we’re home.',
'So, how would you feel about another year of high school?',
'Under my close, personal supervision.',
'Hi.',
'Thank God you’re all right. You know, we’ve been worried sick about you.',
'Thank you, Mr. Rooney, for driving him home.',
'Now I want you to go upstairs and get in bed.',
'Um… Huh…',
'Scoot!',
'Can you imagine someone as sick as Ferris trying to walk home from the hospital?',
'Oh, kids.',
'By the way, Mr. Rooney. You left your wallet on the kitchen floor.',
'Aargh!',
'Honey…',
'He’s still awfully warm.',
'How do you feel?',
'One hundred and fifty percent better, thank you.',
'Please. Don’t make me stay home again.',
'I want to go to school.',
'I have to graduate in June. And… And I… I want…',
'Ferris, you’re sick.',
'Now don’t go pushin’ it and makin’ yourself worse.',
'Ah, maybe you’re right, Dad.',
'I know I’m right, pal.',
'How’d you get to be so sweet?',
'Years of practice.',
'Oh…',
'Hmm, blankie.',
'Get well.',
'Listen, I’m going to get myself settled, and I’ll bring a hot cup of soup, okay?',
'Oo-hoo!',
'Yup. I said it before, and I’ll say it again.',
'Life moves pretty fast. You don’t stop and look around once in a while, you could miss it.',
'Four years of chasing this kid… Four years…',
'Hey, Mr. Rooney. What’s goin’ on?',
'Did you get in a fight?',
'Want a lift?',
'I bet you never smelled a real school bus before.',
'Gummy bear?',
'They’ve been in my pocket. They’re real warm and soft.',
'You’re still here?',
'It’s over.',
'Go home.',
'Go.',
];
