module.exports = ['Aaah!','Aargh!',
'GHOSTBUSTERS',
'All right. I’m gonna turn over the next card.',
'I want you to concentrate. I want you to tell me… what you think it is.',
'Square.',
'Good guess. But wrong.',
'Ah!',
'Clear your head.',
'All right. Tell me what you think it is.',
'Is it a star?',
'It is a star. Very good. That’s great.',
'Okay. All right.',
'Think hard. What is it?',
'Circle.',
'Oo… Close. But definitely wrong.',
'Oh!',
'Okay… All right. Ready?',
'Yeah.',
'All right.',
'What is it?',
'Come on.',
'Figure eight.',
'Incredible. That’s five for five. You can’t see these, can you?',
'No, no.',
'You’re not cheating me, are you?',
'No, I swear they’re just coming to me.',
'Okay… Nervous?',
'Yes… I don’t like this.',
'You only have 75 more to go, okay? What’s this one?',
'It’s… It’s… It’s a couple wavy lines.',
'Sorry. This isn’t your lucky day.',
'I know. Uh! Um… Wait, ah, um… Wait, uh…! I…',
'Hey!! I’m getting a little tired of this!',
'You volunteered, didn’t you? We’re paying, aren’t we?',
'Yeah, but I didn’t know you were gonna give me electric shocks!',
'What are you trying to prove here, anyway?!',
'I’m studying the effect of negative reinforcement on ESP ability.',
'The effect?! I’ll tell you what the effect is! It’s pissing me off!',
'Well, then maybe my theory is correct!',
'You can keep the five bucks! I’ve had it.',
'I will, mister!',
'You may as well get used to that.',
'It’s the kind of resentment that your ability will provoke in some people.',
'Do you think I have it, Dr. Venkman?',
'You’re no fluke, Jennifer.',
'This is it! This is definitely it!',
'Did those UV lenses come in for the video camera? And that blank tape, I need it, the one you erased yesterday.',
'Will you excuse me for a second?',
'Sure.',
'I’m right in the middle of something, Ray.',
'Uh, I need more time with this subject. Could you come back in an hour, hour and a half?',
'Peter, at 1:40 p.m., at the main branch of The New York Public Library on Fifth Avenue, ten people witnessed a free-floating, full-torso, vaporous apparition.',
'It blew books off shelves from 20 feet away and scared the socks off some poor librarian.',
'I’m very excited. I’m very pleased. I want you to get right down there, check it out, and get back to me, okay—',
'No, no—',
'Get right back to me—',
'No. Peter, you’re coming with us on this one.',
'Spengler went down there. He took PKE valences, went right off the top of the scale. Buried the needle.',
'We’re close on this one. I can feel it.',
'I can feel it. We’re very, very close.',
'I have to go now, Jennifer. But I’d like to work with you some more. Perhaps you could come back this evening, say at—',
'8:00?',
'I was just going to say, “8:00?” You are a legitimate phenomenon.',
'As a friend, I have to tell you you finally gone around the bend on this ghost business.',
'You guys have been running your ass off, meetin’ and greetin’ every schizo in the five boroughs who says he has a paranormal experience—what have you seen?',
'Of course, you forget, Peter: I was present at an undersea, unexplained mass sponge migration.',
'Oh… Ray, the sponges migrated about a foot an’ a half.',
'Ooo… Ooo… Egon…',
'Oh, you’re here!',
'Yeah, what have you got?',
'This is big, Peter. This is very big. There’s definitely something here.',
'Egon, this reminds me of the time you tried to drill a hole through your head. Remember that?',
'That would’ve worked if you hadn’t stopped me.',
'Hello. I’m Roger Delacorte. Are you the men from the university?',
'Yes. I’m Dr. Venkman. Dr. Stantz. Egon.',
'Thank you for coming. I hope we can clear this up quickly and… quietly.',
'Let’s not rush things. We don’t even know what you have yet.',
'I don’t remember seeing any legs, but it definitely had arms, because it reached out for me.',
'Arms?! I can’t wait to get a look at this thing.',
'Alice, I’m gonna ask you a couple of standard questions, okay?',
'Have you or any member of your family ever been diagnosed schizophrenic, mentally incompetent?',
'My uncle thought he was St. Jerome.',
'I’d call that a big yes.',
'Uh… Are you habitually using drugs, stimulants, alcohol?',
'No.',
'No, no. Just asking.',
'Are you, Alice, menstruating right now?',
'What has that got to do with it?',
'Back off, man. I’m a scientist.',
'Ray! It’s moving! Come on.',
'Look!',
'This is hot, Ray.',
'Symmetrical book-stacking. Just like the Philadelphia Mass Turbulence of 1947.',
'You’re right, no… human being would stack books like this.',
'Listen! You smell something?',
'Talk about telekinetic activity. Look at this mess!',
'Raymond, look at this.',
'Ectoplasmic residue!',
'Venkman, get a sample of this.',
'It’s the real thing.',
'Somebody blows their nose, and you wanna keep it?',
'I’d like to analyze it.',
'There’s more over here!',
'I’m getting stronger readings here.',
'Oh, ah… Aw… Oh… Ah…!',
'This way.',
'Come on!',
'Egon. Your mucus.',
'Eee!',
'This happen to you before?',
'Huh. First time.',
'It’s here.',
'A full-torso apparition. And it’s real.',
'So, what do we do?',
'Could you come over here and talk to me for a second, please?',
'Could you just come over here for a second, please?',
'Right over here. Come here, Francine. Come here.',
'What do we do?!',
'I don’t know. What do you think?',
'Stop that!',
'We’ve got to make contact. One of us should actually try to speak to it.',
'Good idea.',
'Hello. I’m Peter. Where are you from? Originally.',
'Shhh.',
'All right. Okay. The usual stuff isn’t working.',
'Okay. I have a plan. I know exactly what to do.',
'Now stay close. Stay close.',
'I know. Do exactly as I say.',
'Get ready. Ready?',
'Get her!',
'Aargh!!',
'Oh! Ohh!!',
'You see it?! What was it?!',
'We’ll get back to you!',
'What?!',
'Hee hee hee… “Get her!”',
'That was your whole plan, “Get her.”',
'It was scientific.',
'I—I just got overexcited.',
'But wasn’t it incredible, Pete? I mean, we actually touched the etheric plane. You know what this could mean to the university?',
'Yeah, it’s gonna be bigger than the microchip. Ray, I’m very excited.',
'I wouldn’t say the experience was completely wasted.',
'According to these readings, I think we have an excellent chance of actually catching a ghost and holding it indefinitely.',
'Well, this is great. If the ionization rate is constant for all ectoplasmic entities, we could really bust some heads!',
'In a spiritual sense, of course.',
'Spengs, you serious about this catching a ghost?',
'I’m always serious.',
'Egon, I’m gonna take back some of the things I’ve said about you.',
'You—You’ve earned it.',
'The possibilities are unlimitless—Hey, Dean Yeager!',
'I trust you’re moving us to better quarters on campus.',
'No, you’re being moved off campus.',
'The board of regents has decided to terminate your grant. You are to vacate these premises immediately.',
'This is preposterous. I demand an explanation.',
'Fine… This university will no longer continue any funding of any kind for your group’s activities.',
'But the kids love us.',
'Dr. Venkman. We believe that the purpose of science is to serve mankind.',
'You, however, seem to regard science as some kind of dodge or hustle.',
'Your theories are the worst kind of popular tripe. Your methods are sloppy. And your conclusions are highly questionable.',
'You are a poor scientist, Dr. Venkman.',
'I see.',
'And you have no place in this department… or in this university.',
'This is a major disgrace. Forget MIT or Stanford now. They wouldn’t touch us with a ten-meter cattle prod.',
'You’re always so concerned about your reputation. Einstein did his best stuff when he was a patent clerk.',
'You know how much a patent clerk earns?',
'No!',
'Personally, I liked the university. They gave us money and facilities. We didn’t have to produce anything.',
'You’ve never been out of college. You don’t know what it’s like out there.',
'I’ve worked in the private sector. They expect results.',
'For whatever reasons, Ray, call it… fate, call it luck, call it karma…',
'I believe that everything happens for a reason. I believe that we were destined to get thrown out of this dump.',
'For what purpose?',
'To go into business for ourselves.',
'This ecto-containment system that Spengler and I have in mind is gonna require a load of bread to capitalize. Where are we gonna get the money?',
'I don’t know. I don’t know.',
'You’re never gonna regret this, Ray.',
'My parents left me that house. I was born there.',
'You’re not gonna lose the house. Everybody has three mortgages nowadays.',
'But at 19%? You didn’t even bargain with the guy.',
'Ray, for your information, the interest rate alone for the first five years comes to $95,000.',
'Will you guys relax? We are on the threshold of establishing the indispensable defense science of the next decade: professional paranormal investigations and eliminations.',
'The franchise rights alone will make us rich beyond our wildest dreams.',
'There’s office space, sleeping quarters, and showers on the next floor. And there’s a full kitchen on the top level.',
'It just seems a little pricey for a unique fixer-upper opportunity, that’s all.',
'What do you think, Egon?',
'I think this building should be condemned.',
'There’s metal fatigue in all the load-bearing members. The wiring is substandard. It’s completely inadequate for our power needs. And the neighborhood is like a demilitarized zone.',
'Hey, does this pole still work?!',
'Wow! This place is great! When can we move in?! You gotta try this pole! I’m gonna get my stuff!',
'Hey! We should stay here—tonight! Sleep here! You know, to try it out!',
'I think we’ll take it.',
'Good.',
'Oh, hi.',
'Oh, Dana, it’s you.',
'Oh, hi, yes, Louis. It’s me.',
'I thought it was the drugstore.',
'Oh, are you sick?',
'Oh, no, no, I’m fine, I feel great. Just ordered some more vitamins and stuff.',
'I was just exercising. I taped “:20 Minute Workout” on my machine and played it back at high speed, so it only took ten minutes. I got a great workout.',
'Good…',
'You want to come in for a mineral water or somethin’?',
'Oh, I’d really like to, um, Louis, but I have to go to rehearsal now, excuse me.',
'No sweat. I’ll take a rain check on that. I always have plenty of low-sodium mineral water and other nutritious foods in the house. But you already know that.',
'Yeah, I know that.',
'Listen, that reminds me. I’m having a big party for all my clients. It’s my fourth anniversary as an accountant, you know. And even though you do your own tax return—which you shouldn’t do—I’d like you to stop by, bein’ that you’re my neighbor and all.',
'Well, thank you, Louis. I’ll really try to stop by.',
'Listen, that reminds me. You shouldn’t leave your TV on so loud when you go out. The creep down the hall phoned the manager.',
'That’s strange. I didn’t realize I left it on.',
'Oh, yeah. You know what I did? I climbed on the ledge and tried to disconnect the cable, but I couldn’t get in. So, you know what I did? I turned up my TV real loud too—',
'Bye, Louis.',
'—so everyone would think both our TVs had somethin’ wrong with them.',
'Okay, so, I’ll see you later, huh? I’ll give you a call.',
'I gotta have a shower.',
'Are you troubled by strange noises in the middle of the night?',
'Do you experience feelings of dread in your basement or attic?',
'Have you or any of your family ever seen a spook, specter, or ghost?',
'If the answer is “yes”, then don’t wait another minute. Pick up your phone and call the professionals.',
'Ghostbusters.',
'Our courteous and efficient staff is on call twenty-four hours a day to serve all your supernatural-elimination needs.',
'We’re ready to believe you!',
'Oh!',
'Zuul!',
'Aaah!',
'You don’t think it’s too subtle, Marty? You don’t think people are gonna drive down and not see the sign?',
'You can’t park that here!',
'Everybody can relax, I found the car.',
'Needs some suspension work… and shocks and, uh, brakes, brake pads, linings, steering box, transmission, rear end…',
'How much?',
'Only 4800.',
'Maybe new rings, also mufflers, a little wiring…',
'Janine, any calls?',
'No.',
'Any messages?',
'No…',
'Any customers?',
'No, Dr. Venkman.',
'It’s a good job, isn’t it?',
'Type something, will you? We’re paying for this stuff.',
'Don’t stare at me. You’ve got the… bug eyes.',
'Janine? Sorry about the “bug eyes” thing. I’ll be in my office.',
'You’re very handy. I can tell.',
'I bet you like to read a lot too.',
'Print is dead.',
'Oh, that’s very fascinating to me. I read a lot myself. Some people think I’m too intellectual. But I think it’s a fabulous way to spend your spare time.',
'I also play racquetball. Do you have any hobbies?',
'I collect spores, molds, and fungus.',
'Hello?',
'Oh, excuse me. Is this—this is the Ghostbusters’ office?',
'Yes, it is. Can I help you?',
'I don’t have an appointment. I’d like to talk to someone, please.',
'I’m Peter Venkman. May I help you?',
'Um… Well, uh… I don’t know. I—What I have to say may sound a little unusual.',
'Oh, it’s all we get, day in, day out, around this place.',
'Come into my office, Miss…',
'Uh, Barrett. Dana Barrett.',
'And this voice said “Zuul”. And then I slammed the refrigerator door, and I left. That was two days ago, and I—I haven’t been back to my apartment.',
'Generally, you don’t see that behavior in a major appliance. What do you think it was?',
'Well, if I knew what it was, I wouldn’t be here.',
'Egon, what do you think?',
'She’s telling the truth. At least she thinks she is.',
'Well, of course I’m telling the truth! Wha—Who would make up a story like that?',
'Some are people who just want attention. Others—just nutballs who come in off the street.',
'You know what it could be? Past-life experience intruding on present time.',
'Could be a race memory stored in the collective unconscious. I wouldn’t rule out clairvoyance or telepathic contact either.',
'I’m sorry, I don’t believe in any of those things.',
'Well, that’s all right. I don’t either.',
'But there are some things we do—standard procedures—in a case like this, which often bring us results.',
'Well, I could go to Hall of Records and check out the structural details in the building. Eh, maybe the building itself has a history of psychic turbulence.',
'Right. Good idea.',
'I could search “Zuul” in the usual literature.',
'“Spates’ Catalogue”.',
'“Tobin’s Spirit Guide”.',
'Yeah.',
'Tell you what. I’ll take Miss Barrett back to her apartment and check her out.',
'I’ll go check out Miss Barrett’s apartment.',
'Okay?',
'Okay… Thank you.',
'It’s okay.',
'Please, let me. If something’s gonna happen here, I want it to happen to me first.',
'That’s the closet.',
'They hate this. I like to torture ‘em.',
'That’s right, boys. It’s Dr. Venkman!',
'Lot of space. Just you?',
'Yes.',
'Good.',
'What is that thing you’re doing?',
'It’s technical. It’s one of our little toys.',
'I see.',
'That’s the bedroom. But nothing ever happened in there.',
'What a crime.',
'You know, you don’t act like a scientist.',
'They’re usually pretty stiff.',
'You’re more like a game-show host.',
'That’s the kitchen, huh?',
'Dana. Are these the eggs?',
'Yes. See, I was over there, and these eggs jumped out of their shells and started to cook on the counter.',
'That is weird.',
'And that’s when I started to hear that awful noise coming from the refrigerator.',
'Dr. Venkman, you’ve come all this way, would you like to check the refrigerator?',
'Better check the fridge. Good call.',
'Oh, my God. Look at all the junk food.',
'No! God damn it! Look, this wasn’t h—!',
'You actually eat this stuff?',
'Look, this wasn’t here, there was nothing here! There was a space, and there was a—a building or something with flames coming out of it! And there were creatures writhing around, and they were growling and snarling! And there were flames, and I heard a voice say, “Zuul”!',
'It was right here.',
'I’m sorry, I’m not getting any reading.',
'Well, are you sure you’re using that thing correctly?',
'Well, there’s n—I think so. But I’m sure there are no animals in there.',
'Well, that’s great. Either I have a monster in my kitchen, or I’m completely crazy.',
'I don’t think you’re crazy.',
'Oh, good. That makes me feel so much better.',
'Let me tell you something about myself! I come home from work to my place, and all I have is my work! There’s nothing else in my life!',
'Dr. Venkman—',
'I meet you, and I say, “My God, there’s someone with the same problem I have.”',
'Yes, we both have the same problem: you.',
'I’m gonna go for broke.',
'I am madly in love with you.',
'I don’t believe this. Will you please leave?',
'And then she threw me out of her life.',
'She thought I was a creep. She thought I was a geek, and she probably wasn’t the first.',
'You are so odd.',
'No.',
'I’ve got it!',
'No, no, no, no.',
'I’ll prove myself to you.',
'That’s not necessary.',
'Yeah, I’ll solve your little problem.',
'Okay.',
'And then you’ll say, “Pete Venkman’s a guy who can get things done.”',
'Right.',
'“I wonder what makes him tick.”',
'I wonder.',
'“I wonder if he’d be interested in knowing what makes me tick.”',
'Right…',
'I’ll bet you’re gonna be thinking about me after I’m gone.',
'I bet I am.',
'No kiss?',
'To our first customer.',
'To our first and only customer.',
'I’m gonna need to draw some petty cash. I should take her out to dinner, we don’t want to lose her.',
'Uh, this magnificent feast here represents the last of the petty cash.',
'Hey, slow down. Chew your food.',
'Hello, Ghostbusters.',
'Yes, of course they’re serious.',
'You do?',
'You have?',
'No kidding!',
'Uh-huh. Well, just, uh, just give me the address.',
'Yes, of course. Oh, they’ll be totally discreet.',
'Thank you.',
'We got one!!',
'It’s a call!',
'Come on!',
'Hey, anybody see a ghost?!',
'Uh, thank you for coming so quickly.',
'Jeez—!',
'The guests are asking questions, and I’m running out of excuses.',
'Has it happened before?',
'Well, most of the original staff knows about the twelfth floor.',
'Uh-huh.',
'The disturbances, I mean.',
'Yeah…',
'But it’s been quiet for years—up until two weeks ago.',
'It was never, ever this bad, though.',
'Yeah.',
'Did you ever report it to anyone?',
'No! Heavens, no.',
'No!',
'The owners don’t like us to even talk about it.',
'No.',
'I hoped we could take care of this quietly.',
'It’s done.',
'Tonight.',
'Yes, sir. Don’t worry. We handle this kind of thing all the time.',
'What are you supposed to be, some kind of a cosmonaut?',
'Ha. No, we’re exterminators. Somebody saw a cockroach up on twelfth.',
'That’s gotta be some cockroach.',
'Bite your head off, man.',
'Going up?',
'I’ll take the next one.',
'You know, it’s just occurred to me, we really haven’t had a completely successful test of this equipment.',
'I blame myself.',
'So do I.',
'Ah, no sense worrying about it now.',
'Why worry? Each of us is wearing an unlicensed nuclear accelerator on his back.',
'Yep. Let’s get ready. Switch me on.',
'What the hell are you doin’?',
'Sorry.',
'Sorry!',
'I’m sorry.',
'We thought you were someone else.',
'Successful test.',
'I guess so. Ah… I think we’d better split up.',
'Good idea.',
'Yeah. We can do more damage that way.',
'Venkman? Venkman!',
'Disgusting blob. I’m gonna have to hold him myself.',
'Come in, Ray.',
'Venkman! I saw it! I saw it! I saw it!',
'It’s right here, Ray. It’s looking at me.',
'He’s an ugly little spud, isn’t he?',
'I think he can hear you, Ray.',
'Don’t move. It won’t hurt you.',
'Aah! Ah! Aaah!',
'Venkman! Venkman! Pete!',
'Venkman, what happened? Are you okay?',
'He slimed me.',
'That’s great! Actual physical contact! Can you move?',
'Ray, Ray! Come in, please!',
'I feel so funky.',
'Spengler! I’m with Venkman! He got slimed!',
'That’s great, Ray. Save some for me.',
'Get down here, right away! It just went into a ballroom.',
'Okay, we’ll be right there.',
'Okay, sir. If you and your staff could please wait out here, we’ll take care of everything.',
'There it is! On the ceiling!',
'That’s the one that got me.',
'All right, boys. Ready? Throw it!',
'I did that! I did that! That’s my fault!',
'It’s okay. The table broke the fall.',
'There’s something very important I forgot to tell you.',
'What?',
'Don’t cross the streams.',
'Why?',
'It would be bad.',
'I’m fuzzy on the whole good/bad thing. What do you mean, “bad”?',
'Try to imagine all life as you know it stopping instantaneously and every molecule in your body exploding at the speed of light.',
'Total protonic reversal.',
'Right, that’s bad. Okay, all right, important safety tip. Thanks, Egon.',
'All right—Ray, take the left. Egon, take the right.',
'‘Kay, Ray, give me one high and outside.',
'Ray!',
'Egon!',
'Okay, all right, all right, hold, hold, hold, oh, oh, oh, oh…!',
'Nice shootin’, Tex!',
'I assure you, Mrs. Van Hoffman, there is no problem with the room. It will be ready promptly at time as soon as your guests are with us.',
'The last throw took something out of him, but he’s gonna move!',
'I need some—I need some room to put the trap down! Give me some room!',
'You’ll excuse me, please.',
'We gotta get this in the clear.',
'Wait, wait, wait, wait, wait!',
'I always wanted to do this. And…',
'The flowers are still standing!',
'Okay, on my go-signal.',
'Spengler. I want a confinement stream from you, okay? Go!',
'Okay. Hold him up there! He’s gonna move. Hold him up. Go!',
'It’s working, Ray.',
'Start bringin’ him down. Start bringin’ him down. You got him. Don’t cross the stream.',
'Maybe now you’ll never slime a guy with a positron collider, huh?',
'Venkman, shorten your stream. I don’t want my face burned off.',
'All right, I’m opening the trap now. Don’t look directly into the trap.',
'I looked at the trap, Ray.',
'Turn your streams off as soon as I close the trap.',
'Get ready… I’m closing it… Now!',
'It’s in there.',
'Hey!',
'Well, that wasn’t such a chore now, was it?',
'Mr. Smith, quickly. I want that door open now. Donald, stand over there.',
'We came, we saw, we kicked its ass!',
'Did you see it? What is it?',
'We got it!',
'What is it? Will there be any more of them?',
'Sir, what you had there was what we refer to as a focused, non-terminal, repeating phantasm, or a class-five, full-roaming vapor. Real nasty one too.',
'And now… let’s talk seriously.',
'Now, for the entrapment, we’re gonna have to ask you for four big ones, $4,000 for that.',
'But we are having a special this week on proton charging and storage of the beast. And that’s only gonna come to $1,000, fortunately.',
'$5,000? I had no idea it’d be so much. I won’t pay it.',
'Well, that’s all right. We can just put it right back in there. Thank you.',
'Well, we certainly can, Dr. Venkman.',
'No, no, no, no! All right! Anything.',
'Thanks so much.',
'Thank you. Hope we can help you again.',
'Coming through! One class-five, free-roaming vapor…!',
'Good morning, I’m Roger Grimsby. Today the entire eastern seaboard is alive with talk of incidents of paranormal activity. Alleged ghost-sightings and related supernatural occurrences have been reported across the entire tri-state area. Seems everybody…',
'Well, everybody has heard ghost stories around the campfire. Heck, my grandma used to spin yarns about a spectral locomotive that would rocket past the farm where she grew up. But now, as if some unforeseen authority…',
'Stand aside, please!',
'Hi, this is Larry King. The phone-in topic: ghosts and ghostbusting. The controversy builds, more sightings are reported. Some maintain that these professional paranormal eliminators in New York are the cause of it all.',
'I got it! I got it! Pete? Ray?',
'Still making headlines all across the country, the Ghostbusters are at it again. This time at the dance club The Rose.',
'The boys in gray slugged it out with a pretty pesky poltergeist, then stayed to dance the night away with some of the ladies who witnessed the disturbance. This is Casey Kasem. Now on with the countdown.',
'Twenty-four hours a day, seven days a week. No job is too big. No fee is too big.',
'Is it just a mist, or does it have arms and legs?',
'As they say in TV, I’m sure there’s one big question on everybody’s mind, and I imagine you are the man to answer that: How is Elvis, and have you seen him lately?',
'Do you believe in UFOs, astral projections, mental telepathy, ESP, clairvoyance, spirit photography, telekinetic movement, full-trance mediums, the Loch Ness monster, and the theory of Atlantis?',
'Uh, if there’s a steady paycheck in it, I’ll believe anything you say.',
'I gotta get some sleep. I’m dying.',
'You don’t look good.',
'I don’t?',
'Well, you looked better. You didn’t used to look like this.',
'Yes, can—can you hold, please?',
'Here’s the paper on the Brooklyn. She paid with Visa.',
'Here’s tonight’s worksheet.',
'Oh, great. Two more free repeaters.',
'This is Winston Zeddemore. He’s here about the job.',
'Beautiful. You’re hired. Ray Stantz, Pete Venkman.',
'Congratulations.',
'Can you help me, please?',
'Welcome aboard.',
'I don’t know where they get these guest conductors. I’m mean, someone should tell them it’s not gonna do him much good to scream at us in German.',
'Well, I don’t think that the man is competent to conduct a major symphony orchestra.',
'Um, could you wait here a minute?',
'Huh? Uh, sure.',
'Dr. Venkman, this is a surprise.',
'That was a wonderful rehearsal.',
'You heard that?',
'Yes. You’re the best one in your row.',
'Oh, thank you. You’re good. Most people can’t hear me with the whole orchestra playing.',
'Ah, I don’t have to take this abuse. I got hundreds of people dying to abuse me.',
'I know. You’re a big celebrity now. Do you have some information for me on my case?',
'Who’s the stiff?',
'The stiff happens to be one of the finest musicians in the world.',
'Do you have information for me, please?',
'Well, sure, but I prefer to give it to you in private.',
'Why don’t you tell me now?',
'Well, okay. I found the name Zuul for ya.',
'Well, the name Zuul refers to a demigod worshiped around 6000 BC by the… What’s that word?',
'“Hittites”.',
'Hittites, Mesopotamians, and Sumerians.',
'“Zuul was the minion of Gozer.” What’s Gozer?',
'Gozer was very big in Sumeria. Big guy.',
'Well, what’s he doing in my icebox?!',
'I’m working on that. If we could get together Thursday night, I’m thinking nine-ish, you know, we could exchange information.',
'I can’t see you Thursday. I’m… I’m… I’m busy.',
'Miss Barrett, you seem to think there is something wrong up here that says in your mind, “He enjoys taking his evenings off and spending it with his clients.”',
'No. I’m making a special exception in your case because… I respect you. It’s corny, but I respect you as an artist.',
'And as a dresser too. This is a magnificent coordination you have going here today.',
'Oh, God. Okay. I’ll, uh… I’ll see you Thursday.',
'I’ll bring the “Roylance Guide”, and we’ll eat and read.',
'So who the hell is that?',
'He’s just a friend.',
'A friend?',
'An old friend.',
'Ah, well, I’ll see you Thursday!',
'I’m sorry I didn’t get to meet you, sir! I’m glad you’re feeling much better! You’re still very pale, though! A little sun!',
'Well, what does he do?',
'Well, he’s a—a scientist.',
'This is where we store all the vapors and entities and slimers that we trap. Very simple, really.',
'A loaded trap here. Open, unlock the system. Insert the trap. Release. Close, lock the system. Set your entry grid. Neutronize your field. And…',
'The light is green, trap is clean. Ghost is incarcerated here in our custom-made storage facility.',
'There’s a man from the EPA here to see you. He’s waiting in your office.',
'EPA? What’s he want?',
'I don’t know. All I do know is I’ve been working two weeks without a break, and you promised me you’d hire more help.',
'Janine, someone with your qualifications would have no trouble finding a top-flight job in either the food service or housekeeping industries.',
'Are you gonna answer that?',
'I’ve quit better jobs than this.',
'Ghostbusters! What do you want?',
'Can I help you?',
'I’m Walter Peck. I represent the Environmental Protection Agency, the Third District.',
'Great. How’s it going down there?',
'Are you Peter Venkman?',
'Yes, I’m… Dr. Venkman.',
'Exactly what are you a doctor of, Mr. Venkman?',
'Well, I have Ph.D.’s in parapsychology and psychology.',
'I see. And now you catch ghosts.',
'Yeah, you could say that.',
'And how many ghosts have you caught, Mr. Venkman?',
'I’m not at liberty to say.',
'And where do you put these ghosts… once you catch them?',
'Into a storage facility.',
'And would this storage facility be located on these premises?',
'Yes.',
'And may I see… this storage facility?',
'No.',
'And why not, Mr. Venkman?',
'Because you did not use the magic word.',
'What is… the magic word, Mr. Venkman?',
'“Please”.',
'May I please… see the storage facility, Mr. Venkman?',
'Why do you want to see the storage facility?',
'Well, because I’m curious.',
'I want to know more about what you do here.',
'Frankly there’ve been a lot of wild stories in the media, and we want to assess any possible environmental impact from your operation.',
'For instance, the presence of noxious, possibly hazardous waste chemicals in your basement.',
'Now you either show me what is down there, or I come back with a court order.',
'You go get a court order, and I’ll sue your ass for wrongful prosecution!',
'You can have it your way, Mr. Venkman.',
'I’m worried, Ray. It’s crowded in there, and all my data points to something big on the horizon.',
'What do you mean, uh, “big”?',
'Well, let’s say this Twinkie represents the normal amount of psychokinetic energy in the New York Area.',
'According to this morning’s sample, it would be a Twinkie… 35 feet long, weighing approximately 600 pounds.',
'That’s a big Twinkie.',
'We could be on the verge of a fourfold cross-rip, a PKE surge of incredible, even dangerous proportions.',
'We just had a visit from the Environmental Protection Agency. How’s the grid holdin’ up?',
'It’s not good.',
'Tell him about the Twinkie.',
'What about the Twinkie?',
'Oh, Dana, it’s you!',
'Hello, Louis.',
'You gotta come in here, you’re missin’ a classic party!',
'Yes, well, I would, Louis, but I have a date coming.',
'You made a date… tonight?',
'Well, I’m—I—I’m sorry, Louis. I forgot.',
'Aw, that’s okay. You can bring him along.',
'All right, maybe we’ll stop by, okay?',
'That’s great! I’ll tell everybody you’re coming! We’re gonna play Twister, we’re gonna do some break-dancin’.',
'Hey, e—',
'Hey, let me in! It’s Louis! Somebody, let me in!!',
'Hello?',
'Oh, hi, Mom, uh… I’ve been busy.',
'Well, uh, no, everything is fine.',
'Yeah, no, just, uh, that one time.',
'Oh, I am.',
'I will.',
'I won’t. Mom, um, I have to go. I have a date.',
'Yes. No, uh, no one you know. It’s, uh…',
'Well, he’s, uh, he’s a Ghostbuster.',
'Those guys on TV.',
'Yes, well, I’ll have to let you know.',
'Okay. Love to Dad.',
'Right. Bye. Bye.',
'Oh, shit.',
'Oh—aaah!! Aaah!! Aaaah!!',
'Do you have any Excedrin or Extra Strength Tylenol?',
'Oh, gee. I think all I got is acetylsalicylic acid, generic. See, I can get 600 tablets of that for the same price as 300 of the name brand.',
'That makes good financial sense, good advice.',
'Hey, this is real smoked salmon from Nova Scotia, Canada, 24.95 a pound. It only cost me 14.12 after tax, though.',
'I’m giving this as a promotional expense. That’s why I invited clients instead of friends. You havin’ a good time, Marv?',
'How you doing? Why don’t you have some of the Brie? It’s at room temperature.',
'You think it’s too warm in here for Brie?',
'Louis, I’m going home.',
'Oh, don’t leave yet. Listen, maybe if we start dancing other people will join in.',
'Okay.',
'Oh, don’t move. I just got to get the door.',
'Ted! Annette!',
'Hi.',
'Hello, Lewis.',
'Glad you could come. How you doin’? Give me your coats.',
'Everybody, this is Ted and Annette Fleming.',
'How are you?',
'Ted has a small carpet-cleaning business in receivership. Annette’s drawing a salary from a deferred bonus from two years ago.',
'They got 15,000 left on the house at eight percent. So they’re okay!',
'So, does anybody want to play Parcheesi?',
'Okay, who brought the dog?',
'Ah!',
'Oh!',
'Help! There’s a bear loose in my apartment! Help! Help!! Help!!',
'What?',
'A bear in his apartment!',
'I’m gonna bring this up at the tenants’ meeting. There’s not supposed to be any pets in the building.',
'Let me in. There’s gotta be a way in here. I gotta get in.',
'Please! Somebody! Let me in!',
'Nice doggy. Cute little pooch. Maybe I got a Milk-Bone.',
'Aargh!!',
'Hey, what happened?',
'Some moron brought a cougar to a party, and it went berserk.',
'Hi, I’m going up to Dana Barrett’s. Okay.',
'Hello?',
'That’s a different look for you, isn’t it?',
'Are you the Keymaster?',
'Not that I know of.',
'Are you the Keymaster??',
'Yes… I’m a friend of his. He told me to meet him here. I didn’t get your name.',
'I am Zuul. I am the Gatekeeper.',
'Oh… What are we doing today, Zuul?',
'Prepare for the coming of Gozer.',
'Gozer, huh?',
'The Destructor.',
'Are we still going out?',
'You know, you could pick up the place if you’re expecting someone.',
'Do you want this body?',
'Is this a trick question?',
'I guess the roses worked, huh?',
'Take me now… sub-creature.',
'We never talk anymore.',
'Whoa—! Ooh! Easy…',
'I make it a rule… never to get involved with possessed people.',
'Actually, it’s more of a guideline than a rule.',
'You know, I can—',
'I want you inside me.',
'Hah hah hah… Go ahead—No, I can’t.',
'Sounds like you got at least two people in there already. Might be a little crowded.',
'Come on, I—I—Why don’t you just quit tryin’ to… upset and disturb… Dr. Venkman—and just relax.',
'Lie down there… Relax… Put your hands on your chest…',
'What I’d really like to do is talk to Dana. I want to talk to Dana. Dana, it’s Peter.',
'There is no Dana. There is only Zuul.',
'Oh, Zuulie, you nut.',
'Now come on, come on. I want to talk to Dana. Dana. Just relax. Come on. Dana, Dana. Can I talk to Dana?',
'There is no Dana—only Zuul!',
'What a lovely singing voice you must have.',
'Now I’m gonna count to three, Zuulie. And if I don’t talk to Dana, there’s gonna be some real trouble in this apartment, I think.',
'One… Two… Two and a half…',
'Please come down.',
'I am the Keymaster! The Destructor is coming. The Traveler, the Destroyer.',
'Gatekeeper!',
'I am Vinz. Vinz Clortho, Keymaster of Gozer. Volguus Zildrohar, Lord of the Sebouillia. Are you the Gatekeeper?',
'Hey, he pulls the wagon, I make the deals. You want a ride?',
'Wait for the sign. Then all prisoners will be released.',
'You will perish in flame, you and all your kind! Gatekeeper!',
'What an asshole.',
'Dropping off or picking up?',
'Dropping off.',
'Just a moment.',
'You a Ghostbuster?',
'Yes.',
'We picked up this guy. Now we don’t know what to do with him. Bellevue doesn’t want him. And I’m afraid to put him in the lockup. And I know you guys are into this stuff, so I figured we’d check with you.',
'All right.',
'Are you the Gatekeeper?',
'You better bring him inside.',
'You are so kind to take care of that man. You know, you are a real humanitarian.',
'I don’t think he’s human.',
'What did you say your name was?',
'Vinz Clortho, Keymaster of Gozer.',
'According to this, his name’s Louis Tully. Lives on Central Park West.',
'Do you want some, uh, coffee, Mr. Tully?',
'Do I?',
'Yes, have some.',
'Yes, have some!',
'Vinz. You said before you were waiting for a sign. What sign are you waiting for?',
'Gozer the Traveler. He will come in one of the pre-chosen forms.',
'During rectification of the Vuldronaii, the Traveler came as a large and moving Torb!',
'Then, during the third reconciliation of the last of the Meketrex supplicants, they chose a new form for him, that of a giant Sloar!',
'Many Shubs and Zulls knew what it was to be roasted in the depths of the Sloar that day, I can tell you.',
'Egon.',
'Excuse me.',
'There’s something very strange about that man!',
'Listen, I’m usually very psychic, and I have a terrible feeling that something awful is gonna happen to ya.',
'I’m afraid you’re gonna die.',
'I’ll get it.',
'Hello?',
'Egon. It’s Peter.',
'Thanks, I’ve got it.',
'I have news from the world of Gozer.',
'What is it, Peter?',
'I’m here with Dana Barrett. It seems the Goze has been putting some moves on my would-be girlfriend.',
'How is she?',
'I think we can get her a guest shot on “Wild Kingdom”.',
'I just whacked her up with about 300 cc’s of Thorazine. She’s gonna take a little nap now.',
'But, uh, she says she’s the Gatekeeper. Does that make any sense to you?',
'Some.',
'I just met the Keymaster. He’s here with me now.',
'Oh, wonderful. We have to get these two together.',
'I think that would be extraordinarily dangerous.',
'Okay, well, hold onto him. I’ll be there in a little while.',
'Good.',
'Thank you, Vinz.',
'We have to find Ray. I need him here immediately.',
'Bad news, honey. I gotta go to work. Hey, will you stay here in bed until I get back?',
'Hey, Ray. Do you believe in God?',
'Never met him.',
'Yeah, well, I do. And I love Jesus’s style, you know?',
'This roof cap is made of a magnesium–tungsten alloy.',
'What are you so involved with there?',
'These are blueprints for the structural ironwork in Dana Barrett’s apartment, and they’re very, very strange.',
'Hey, Ray. Do you remember something in the Bible about the last days, when the dead would rise from the grave?',
'I remember Revelations 7:12.',
'“And I looked as he opened the sixth seal. And behold, there was a great earthquake. And the sun became as black as sackcloth. And the moon became as blood.”',
'“And the seas boiled. And the skies fell.”',
'Judgment Day…',
'Judgment Day.',
'Every ancient religion has its own myth about the end of the world.',
'Myth?! Ray, has it ever occurred to you that maybe the reason we’ve been so busy is because the dead have been rising from the grave?',
'How about a little music?',
'Heh. Yeah.',
'This way.',
'Excuse me. Excuse me, just where do you think you’re going?!',
'Step aside, miss, or you’ll be arrested for interfering with a police office—',
'Oh, no! Hold on. I’ve seen TV. I know you can’t come in here without a warrant or a writ or something!',
'Cease-and-desist-all-commerce order, seizure of premises and chattels, ban on the use of public utilities for non-licensed waste handlers, and a federal entry-and-inspection order!',
'Vinz, there’s one more test I’d like to perform—',
'Egon! I tried to stop them! He says they have a warrant.',
'Excuse me, this is private property.',
'Shut this off. Shut these all off.',
'I’m warning you, turning off these machines would be extremely hazardous.',
'I’ll tell you what’s hazardous. You’re facing federal prosecution for at least a half a dozen environmental violations. Now either you shut off these beams, or we shut ‘em off for you.',
'Try to understand, this is a high-voltage laser containment system. Simply turning it off would be like dropping a bomb in the city.',
'Don’t patronize me! I’m not grotesquely stupid, like the people you bilk.',
'At ease, officer. I’m Peter Venkman. I think there’s just been a slight misunderstanding, and I want to cooperate in any way that I can.',
'Forget it, Venkman. You had your chance to cooperate, but you thought it’d be more fun to insult me. Well, now it is my turn, wise-ass.',
'He wants to shut down the protection grid, Peter.',
'You shut that thing down, and we are not gonna be held responsible for whatever happens—',
'On the contrary, you’re gonna be held—',
'No, we won’t be held responsible—',
'Shut it off!',
'Don’t shut it off. I’m warning ya.',
'Um, I’ve—I’ve never seen anything like this. I don’t know—',
'Yeah, I’m not interested in your opinion. Just shut it off.',
'My friend, don’t be a jerk.',
'Step aside!',
'If he does that again, you can shoot him.',
'You do your job, pencil-neck. Don’t tell me how to do mine!',
'Thank you, officer.',
'Shut it off!',
'Oh, shit…',
'Clear the building!!',
'This is it! This is the sign!',
'Yeah, it’s a sign, all right! We’re goin’ out of business.',
'There it is, up there.',
'Yo, officer, what’s goin’ on…?',
'What happened?',
'Storage facility blew. He shut off the protection grid.',
'Oh, great.',
'That’s bad, isn’t it?',
'Yeah.',
'Where’s the Keymaster?!',
'Oh, shit!',
'Who’s the Keymaster?',
'Oh, come on!',
'Hold it!! I want this man arrested!!',
'Captain, these men are in criminal violation of the Environmental Protection Act!! And this explosion is a direct result of it!!',
'Your mother!!',
'Hey! Come on, hold it! Hold it! Come on, you…!',
'Columbia Building, 57th Street. I’m in a hurry, so, uh, let’s not dawdle.',
'Hey, guard! Look, I want to make a phone call.',
'Hey, I just work with these guys, man, I wasn’t even there!',
'The structure of this roof cap is exactly like the kind of telemetry tracker that NASA uses to identify dead pulsars in deep space.',
'Cold-riveted girders… with cores of pure selenium.',
'Everybody getting this so far?!',
'So what? I guess they just don’t make ‘em like they used to, huh?',
'No! Nobody ever made them like this!',
'I mean, the architect was either a certified genius or an authentic wacko.',
'Ray. For a moment… pretend that I don’t know anything about metallurgy, engineering, or physics, and just tell me what the hell is going on.',
'You never studied.',
'The whole building is a huge super-conductive antenna that was designed and built expressly for the purpose of pulling in and concentrating spiritual turbulence.',
'Your girlfriend lives in the corner penthouse of spook central.',
'She’s not my girlfriend.',
'I find her interesting because she’s a client, and because she sleeps above her covers. Four feet above her covers.',
'She barks. She drools. She claws.',
'It’s not the girl, Peter. It’s the building.',
'Something terrible is about to enter our world, and this building is obviously the door.',
'The architect’s name was Ivo Shandor. I found it in “Tobin’s Spirit Guide”.',
'He was also a doctor. Performed a lot of unnecessary surgery.',
'And then in 1920, he started a secret society.',
'Let me guess. Gozer worshipers.',
'Right.',
'No studying.',
'After the First World War, Shandor decided that society was too sick to survive.',
'And he wasn’t alone, he had close to a thousand followers when he died.',
'They conducted rituals up on the roof. Bizarre rituals intended to bring about the end of the world. And now it looks like it may actually happen.',
'So be good! For goodness sake! Whoa, oh! Somebody’s comin’! Somebody’s comin’…!',
'We have to get out of here. We’ve got to find a judge or something here.',
'Hey, wait a minute! Hey, hey, hey, hey, hey! Hold it!',
'Now are we gonna go before a federal judge and say that some moldy Babylonian god is gonna drop in on Central Park West and start tearing up the city?!',
'Sumerian, not Babylonian.',
'Yeah, big difference.',
'Heh. No offense, but I gotta get my own lawyer.',
'Okay, Ghostbusters. Mayor wants to see you guys.',
'Whole island’s goin’ crazy. Let’s go.',
'I gotta split, the mayor wants to rap with me about some things.',
'I am the Keymaster.',
'I am the Gatekeeper.',
'Back. Stay back. Stay back.',
'I got a city blowing up, and you guys are not giving me any answers.',
'All right, we’re blocking the bridges, the roads…',
'The Ghostbusters are here, Mr. Mayor.',
'The Ghostbusters. Okay, the Ghostbusters.',
'Hey. Where’s this Peck?',
'I am Walter Peck, sir. And I’m prepared to make a full report.',
'These men are consummate snowball artists. They use sense and nerve gases to induce hallucinations.',
'People think they’re seeing ghosts. And they call these bozos, who conveniently show up to deal with the problem with a fake, electronic light show.',
'Everything was fine with our system until the power grid was shut off by dickless here.',
'They caused an explosion!',
'Is this true?',
'Yes, it’s true. This man has no dick.',
'You—!',
'Hey, no—!',
'Knock it off! Hey!',
'Break it up! Break it up!',
'All right! All right! All right!',
'Well, that’s what I heard!',
'This is City Hall!',
'Now what am I gonna do here, John?! What is this?!',
'All I know is that was no light show we saw this morning.',
'I’ve seen every form of combustion known to man. But this beats the hell out of me.',
'The walls in the 53rd Precinct were bleeding. How do you explain that?',
'Good afternoon, gentlemen.',
'Oh, Your Eminence.',
'Ah…',
'How are ya, Lenny?',
'You’re lookin’ good, Mike. We’re in a real fix here. What do you think I should do?',
'Lenny. Officially, the church will not take any position on the religious implications of these, uh, phenomena.',
'Personally, Lenny… I think it’s a sign from God. But don’t quote me on that.',
'Now I think that’s a smart move, Mike.',
'Well, I’m not gonna call a press conference and tell everyone to start praying.',
'Uh… I’m, uh, Winston Zeddemore, Your Honor.',
'Look, I’ve only been with the company for a couple weeks. But I gotta tell you, these things are real.',
'Since I joined these men, I have seen shit that’ll turn you white.',
'Well, you could believe Mr. Pecker—',
'My name is Peck.',
'—Or you could accept the fact that this city is headed for a disaster of biblical proportions.',
'What do you mean, “biblical”?',
'What he means is Old Testament, Mr. Mayor.',
'Yes.',
'Real wrath-of-God–type stuff.',
'Exactly.',
'Fire and brimstone coming down from the skies! Rivers and seas boiling!',
'Forty years of darkness! Earthquakes! Volcanoes!',
'The dead rising from the grave!',
'Human sacrifice! Dogs and cats living together! Mass hysteria!',
'Enough! I get the point!',
'But what if you’re wrong?',
'If I’m wrong, nothing happens! We go to jail—peacefully, quietly—we’ll enjoy it!',
'But if I’m right… and we can stop this thing… Lenny…',
'You will have saved the lives… of millions of registered voters.',
'I don’t believe you’re seriously considering listening to these men.',
'Get him outta here.',
'Bye.',
'I’ll fix you, Venkman. I’m gonna fix you.',
'I’m gonna get you a nice fruit basket—I’m gonna miss him!',
'All right, all right.',
'We got work to do. Now what do you need from me?',
'Come on, let’s run some red lights!',
'Hello, New York!',
'Hello, everybody! Whoa!',
'Dr. Ray Stantz, would you please? The heart of the Ghostbusters. Thank you.',
'They love you. They love you here.',
'I like that shirt, friend.',
'Ghostbusters! All right! All right…!',
'Gotta run! Got a date with a ghost!',
'Okay, whatever happens, let’s be professional!',
'We might have to put a little overtime in on this one!',
'Aaaah…!',
'Ghostbusters… Are they all right…?',
'Wait… There they are! Yeah!',
'I was in no way prepared for that!',
'It’s all right! Don’t worry, we’re fine, we can handle it, we can take it! They want to play rough!',
'Ghostbusters! Ghostbusters! Ghostbusters! Ghostbusters! Ghostbusters! Ghostbusters! Ghostbusters! Ghostbusters! Ghostbusters…!',
'Wanna play rough?!',
'Yeah!',
'Let’s do it!',
'Where are we?',
'It looks like we’re in the… teens… somewhere.',
'Well, when we get to twenty, tell me. I’m gonna throw up.',
'Twenty-two. Is this it?',
'Yup.',
'Art deco. Very nice.',
'Where is it?',
'It’s at the end of the hall.',
'Hey, where do these stairs go?!',
'They go up.',
'Okay, go ahead. Come on, go ahead. Watch it. Go ahead.',
'Dana!',
'Okay. So… she’s a dog.',
'It’s a girl.',
'It’s Gozer.',
'I thought Gozer was a man.',
'It’s whatever it wants to be.',
'Well, whatever it is, it’s gotta get by us!',
'Right.',
'Go get her, Ray!',
'Gozer the Gozerian?',
'Good evening.',
'As a duly designated representative of the City… County, and State of New York, I order you to cease any and all supernatural activity and return forthwith to your place of origin, or to the nearest convenient parallel dimension.',
'That ought to do it. Thanks very much, Ray.',
'Are you a god?',
'…No.',
'Then… die!!',
'Aargh!!',
'Ray. When someone asks you if you’re a god, you say, “yes”!',
'All right. This chick is toast!',
'Got your stick?',
'Holdin’ it!',
'Heat ‘em up!',
'Smokin’!',
'Make ‘em hard!',
'Ready!',
'Let’s show this prehistoric bitch how we do things downtown.',
'Throw it!',
'Nimble little minx, in’t she?',
'We better go full-stream.',
'Aim for the flattop!',
'Wasn’t so hard.',
'We neutronized it! You know what that means? A complete particle reversal!',
'Eh, we had the tools! We had talent!',
'It’s Miller time!',
'Ray. This looks extraordinarily bad.',
'Oh, no.',
'What?',
'Look out!',
'Sub-creatures!! Gozer the Gozerian, Gozer the Destructor, Volguus Zildrohar the Traveler has come!! Choose and perish!!',
'What do you mean “choose”?! We don’t understand!',
'Choose!! Choose the form of the Destructor!!',
'Oh… I get it! I get it, oh! Very cute!',
'Whatever we think of—if we think of J. Edgar Hoover, J. Edgar Hoover will appear and destroy us, okay?',
'So, empty your heads! Empty your heads! Don’t think of anything, we’ve only got one shot at this!',
'The choice is made!!',
'Whoa! Ho, huh? Whoa!',
'The Traveler has come!!',
'Nobody choosed anything!',
'Did you choose anything?!',
'No!',
'Did you?!',
'My mind is totally blank.',
'I didn’t choose anything!',
'I couldn’t help it.',
'It just popped in there.',
'What?! What just popped in there?!',
'I—I—I tried to think—',
'Look!!',
'No! It can’t be!',
'What is it?!',
'It can’t be!',
'What did you do, Ray?!',
'Ah, shit!',
'It’s the Stay-Puft Marshmallow Man.',
'Well, there’s somethin’ you don’t see every day.',
'I tried to think of the most harmless thing. Something I loved from my childhood. Something that could never, ever possibly destroy us. Mr. Stay Puft.',
'Nice thinkin’, Ray.',
'We used to roast Stay-Puft marshmallows… by the fire at Camp Waconda.',
'Ray, has gone bye-bye, Egon. What have you got left?',
'Sorry, Venkman. I’m terrified beyond the capacity for rational thought.',
'Oh, no.',
'Mother pus-bucket.',
'Nobody steps on a church in my town!',
'One… two… three… roast him!',
'Funny, us going out like this. Killed by a hundred-foot marshmallow man.',
'We’ve been goin’ about this all wrong. This Mr. Stay Puft is okay. He’s a sailor. He’s in New York. We get this guy laid, we won’t have any trouble.',
'I have a radical idea.',
'The door swings both ways. We could reverse the particle flow through the gate.',
'How?',
'We’ll cross the streams.',
'Excuse me, Egon. You said crossing the streams was bad.',
'Cross the streams…',
'You’re gonna endanger us. You’re gonna endanger our client—the nice lady who paid us in advance, before she became a dog.',
'Not necessarily. There’s definitely a very slim chance we’ll survive.',
'I love this plan! I’m excited to be a part of it! Let’s do it!',
'This job is definitely not worth eleven-five a year!',
'Hurry!',
'See you on the other side, Ray.',
'Nice working with you, Dr. Venkman.',
'Let’s turn ‘em on, Spengler!',
'Spark ‘em now, Spengler!!',
'Aahhhhh…!!!',
'Winston… Are you all right?',
'Heh heh… Yeah… yeah…',
'Venkman? Spengler! Venkman! Spengler?',
'Oh, Spengler. Ah, are you okay?',
'I feel like the floor of a taxicab.',
'Venky!',
'Yeah, where are ya?',
'Oh, thank God. Oh. You okay?',
'I’m all right.',
'You all right?',
'I’m all right. You all right?',
'Yeah. You okay?',
'Fine.',
'Oh… Smells like barbecued dog hair.',
'Oh! Venkman. Oh, Venkman, I’m sorry. I’m sorry, I—I just—I just forgot.',
'Look!',
'Somebody turn on the lights! Help! Somebody…!',
'Go check on that little guy!',
'What happened?',
'Oh… Oh… Oh, where am I?',
'Oh… hi.',
'You’re all right.',
'Boy, the superintendent’s gonna be pissed!',
'Are you okay?',
'Who are you guys?',
'We’re the Ghostbusters.',
'Who does your taxes?',
'You know, Mr. Tully, you are a most fortunate individual.',
'I know.',
'You have been a participant in the biggest inter-dimensional cross-rip since the Tunguska Blast of 1909.',
'Felt great.',
'We’d like to get a sample of your brain tissue.',
'Okay.',
'I love this town!! Ha ha!',
'Written by DAN AYKROYD and HAROLD RAMIS',
'Egon! You’re safe!',
'What’s goin’ on?!',
'Anybody want to interview me? I’m an eyewitness! I was up—!',
'I want to go with them in the car.',
'Aah!',
];
