module.exports = [
'THE PRINCESS BRIDE',
'Hi, honey.',
'Hi, Mom.',
'You feeling any better?',
'A little bit.',
'Guess what?',
'What?',
'Your grandfather’s here.',
'Mom, can’t you tell him I’m sick?',
'You’re sick?',
'That’s why he’s here.',
'He’ll pinch my cheek.',
'I hate that.',
'Maybe he won’t.',
'Hey, how is the sickie?',
'I think I’ll leave you two pals alone.',
'I brought you a special present.',
'What is it?',
'Open it up.',
'A book?',
'That’s right.',
'When I was your age, television was called books.',
'And this is a special book.',
'It was the book my father used to read to me when I was sick, and I used to read it to your father.',
'And today, I’m gonna read it to you.',
'Has it got any sports in it?',
'Are you kidding?',
'Fencing, fighting, torture, revenge, giants, monsters, chases, escapes, true love, miracles.',
'Doesn’t sound too bad. I’ll try and stay awake.',
'Well, thank you very much. Very nice of you.',
'Your vote of confidence is overwhelming.',
'All right.',
'“The Princess Bride, by S. Morgenstern.',
'“Chapter one.',
'“Buttercup was raised on a small farm in the country of Florin.',
'“Her favorite pastimes were riding her horse and tormenting the farm boy that worked there.',
'“His name was Westley, but she never called him that.”',
'Isn’t that a wonderful beginning?',
'Yeah, it’s really good.',
'“Nothing gave Buttercup as much pleasure as ordering Westley around.”',
'Farm Boy, polish my horse’s saddle.',
'I want to see my face shining in it by morning.',
'As you wish.',
'“‘As you wish’ was all he ever said to her.”',
'Farm Boy, fill these with water.',
'Please?',
'As you wish.',
'“That day, she was amazed to discover that when he was saying, ‘As you wish,’ what he meant was, ‘I love you.’',
'“And even more amazing was the day she realized she truly loved him back.”',
'Farm Boy?',
'Fetch me that pitcher?',
'As you wish.',
'Hold it. Hold it.',
'What is this? Are you trying to trick me?',
'Where’s the sports?',
'Is this a kissing book?',
'Wait. Just wait.',
'When does it get good?',
'Keep your shirt on. Let me read.',
'“Westley had no money for marriage, “so he packed his few belongings and left the farm to seek his fortune across the sea.',
'“It was a very emotional time for Buttercup.”',
'I don’t believe this.',
'I fear I’ll never see you again.',
'Of course you will.',
'But what if something happens to you?',
'Hear this now.',
'I will always come for you.',
'But how can you be sure?',
'This is true love.',
'Do you think this happens every day?',
'“Westley didn’t reach his destination.',
'“His ship was attacked by the Dread Pirate Roberts, “who never left captives alive.',
'“When Buttercup got the news that Westley was murdered—”',
'Murdered by pirates is good.',
'“—she went into her room and shut the door.',
'“And for days, she neither slept nor ate.”',
'I will never love again.',
'“Five years later, the main square of Florin City was filled as never before to hear the announcement of the great Prince Humperdinck’s bride-to-be.”',
'My people, a month from now, our country will have its five hundredth anniversary.',
'On that sundown, I shall marry a lady who was once a commoner like yourselves.',
'But perhaps you will not find her common now.',
'Would you like to meet her?',
'Yes!',
'My people, the Princess Buttercup!',
'“Buttercup’s emptiness consumed her.',
'“Although the law of the land gave Humperdinck the right to choose his bride, “she did not love him.',
'“Despite Humperdinck’s reassurance that she would grow to love him, “the only joy she found was in her daily ride.”',
'A word, my lady?',
'We are but poor, lost circus performers.',
'Is there a village nearby?',
'There is nothing nearby, not for miles.',
'Then there will be no one to hear you scream.',
'What is that you’re ripping?',
'It is fabric from the uniform of an army officer of Guilder.',
'Who is Guilder?',
'The country across the sea.',
'The sworn enemy of Florin.',
'Go!',
'Once the horse reaches the castle, the fabric will make the prince suspect that the Guilderians have abducted his love.',
'When he finds her body dead on the Guilder frontier, his suspicions will be totally confirmed.',
'You never said anything about killing anyone.',
'I’ve hired you to help me start a war.',
'It’s a prestigious line of work with a long and glorious tradition.',
'I just don’t think it’s right killing an innocent girl.',
'Am I going mad or did the word “think” escape your lips?',
'You were not hired for your brains, you hippopotamic landmass!',
'I agree with Fezzik.',
'The sot has spoken.',
'What happens to her is not truly your concern.',
'I will kill her.',
'And remember this. Never forget this!',
'When I found you, you were so slobbering drunk you couldn’t buy brandy!',
'And you!',
'Friendless. Brainless.',
'Helpless! Hopeless!',
'Do you want me to send you back to where you were?',
'Unemployed? In Greenland?',
'That Vizzini, he can… fuss.',
'Fuss. Fuss.',
'I think he like to scream at us.',
'Probably he means no harm.',
'He’s really very short on charm.',
'You have a great gift for rhyme.',
'Yes. Yes. Some other time.',
'Enough of that!',
'Fezzik, are there rocks ahead?',
'If there are, we’ll all be dead.',
'No more rhymes now, I mean it!',
'Anybody want a peanut?',
'We’ll reach the cliffs by dawn.',
'Why are you doing that?',
'Are you sure nobody’s follow us?',
'That would be inconceivable.',
'Despite what you think, you will be caught.',
'And when you are, the Prince will see you all hanged.',
'Of all the necks on this boat, Highness, the one you should be worrying about is your own.',
'Stop doing that!',
'We can all relax. It’s almost over.',
'You are sure nobody’s follow us?',
'As I told you, it would be absolutely, totally and in all other ways inconceivable.',
'No one in Guilder knows what we’ve done and no one in Florin could have gotten here so fast.',
'Out of curiosity, why do you ask?',
'No reason. Suddenly, I just happen to look behind us and something is there.',
'What?',
'Probably some local fisherman out for a pleasure cruise at night through eel-infested waters.',
'What? What?',
'Go in! Get after her!',
'I don’t swim.',
'I only dog paddle.',
'Veer left!',
'Left! Left!',
'Do you know what that sound is, Highness?',
'Those are the shrieking eels!',
'If you don’t believe me, just wait.',
'They always grow louder when they’re about to feed on human flesh!',
'If you swim back now, I promise no harm will come to you.',
'I doubt you’ll get such an offer from the eels.',
'She doesn’t get eaten by the eels at this time.',
'What?',
'The eel doesn’t get her.',
'I’m explaining to you because you look nervous.',
'I wasn’t nervous.',
'Maybe I was a little bit concerned, but that’s not the same thing.',
'Because we can stop now, if you want.',
'No, you could read a little bit more, if you want.',
'“Do you know what that sound is, Highness?',
'“Those are the shrieking eels.”',
'Look, we’re past that, Grandpa. You read it already.',
'Oh. Oh, my goodness. I did.',
'I’m sorry. I beg your pardon.',
'All right. All right. Let’s see, she was in the water.',
'The eel was coming after her.',
'She was frightened.',
'The eel started to charge her, and then…',
'Put her down. Just put her down.',
'I think he’s getting closer.',
'He’s no concern of ours. Sail on!',
'I suppose you think you’re brave, don’t you?',
'Only compared to some.',
'Look! He’s right on top of us!',
'I wonder if he is using the same wind we are using.',
'Whoever he is, he’s too late.',
'See?',
'The Cliffs of Insanity!',
'Hurry up!',
'Move the thing!',
'And that other thing!',
'Move it!',
'We’re safe.',
'Only Fezzik is strong enough to go up our way.',
'He’ll have to sail around for hours till he finds a harbor.',
'He’s climbing the rope. And he’s gaining on us.',
'Inconceivable.',
'Faster!',
'I thought I was going faster.',
'You were supposed to be this colossus.',
'You were this great legendary thing.',
'And yet, he gains!',
'Well, I’m carrying three people, and he got only himself.',
'I do not accept excuses.',
'I’m just going to have to find myself a new giant, that’s all.',
'Don’t say that, Vizzini. Please?',
'Did I make it clear that your job is at stake?',
'He’s got very good arms.',
'He didn’t fall?',
'Inconceivable.',
'You keep using that word.',
'I do not think it means what you think it means.',
'My God. He’s climbing.',
'Whoever he is, he’s obviously seen us with the Princess and must, therefore, die.',
'You, carry her.',
'We’ll head straight for the Guilder frontier.',
'Catch up when he’s dead.',
'If he falls, fine. If not, the sword.',
'I’m going to duel him left-handed.',
'You know what a hurry we’re in!',
'It’s the only way I can be satisfied.',
'If I use my right, over too quickly.',
'Oh, have it your way.',
'You be careful.',
'People in masks cannot be trusted.',
'I’m waiting!',
'Hello there!',
'Slow going?',
'Look, I don’t mean to be rude, but this is not as easy as it looks, so I’d appreciate it if you wouldn’t distract me.',
'Sorry.',
'Thank you.',
'I don’t suppose you could speed things up?',
'If you’re in such a hurry, you could lower a rope or a tree branch, or find something useful to do.',
'I could do that. I’ve got some rope up here.',
'But I do not think you would accept my help, since I am only waiting around to kill you.',
'That does put a damper on our relationship.',
'But I promise I will not kill you until you reach the top.',
'That’s very comforting, but I’m afraid you’ll just have to wait.',
'I hate waiting.',
'I could give you my word as a Spaniard.',
'No good. I’ve known too many Spaniards.',
'Is there any way you’ll trust me?',
'Nothing comes to mind.',
'I swear on the soul of my father, Domingo Montoya, you will reach the top alive.',
'Throw me the rope.',
'Thank you.',
'We’ll wait—wait—wait—wait—wait until you’re ready.',
'Again, thank you.',
'I do not mean to pry, but you don’t by any chance happen to have six fingers on your right hand?',
'Do you always begin conversations this way?',
'My father was slaughtered by a six-fingered man.',
'He was a great sword maker, my father.',
'When the six-fingered man appeared and requested a special sword, my father took the job.',
'He slaved a year before he was done.',
'I’ve never seen its equal.',
'The six-fingered man returned and demanded it, but at one-tenth his promised price.',
'My father refused.',
'Without a word, the six-fingered man slashed him through the heart.',
'I loved my father.',
'So, naturally, I challenged his murderer to a duel.',
'I failed.',
'The six-fingered man leave me alive.',
'But he gave me this.',
'How old were you?',
'I was eleven years old.',
'When I was strong enough, I dedicated my life to the study of fencing.',
'So, the next time we meet, I will not fail.',
'I will go up to the six-fingered man and say:',
'“Hello. My name is Inigo Montoya. You killed my father. Prepare to die.”',
'You’ve done nothing but study swordplay?',
'More pursue it than study, lately.',
'You see, I cannot find him.',
'It has been twenty years now.',
'I’m starting to lose confidence.',
'I just work for Vizzini to pay the bills.',
'There’s not a lot of money in revenge.',
'Well, I certainly hope you find him someday.',
'You’re ready then?',
'Whether I am or not, you’ve been more than fair.',
'You seem a decent fellow. I hate to kill you.',
'You seem a decent fellow. I hate to die.',
'Begin.',
'You are using Bonetti’s defense against me, huh?',
'I thought it fitting, considering the rocky terrain.',
'Naturally, you must expect me to attack with Capo Ferro.',
'Naturally.',
'But I find that Thibault cancels out Capo Ferro, don’t you?',
'Unless the enemy has studied his Agrippa.',
'Which I have!',
'You are wonderful.',
'Thank you.',
'I’ve worked hard to become so.',
'I admit that you are better than I am.',
'Then why are you smiling?',
'Because I know something you don’t know.',
'And what is that?',
'I am not left-handed.',
'You are amazing.',
'I ought to be, after twenty years.',
'There’s something I ought to tell you.',
'Tell me.',
'I’m not left-handed either.',
'Who are you?',
'No one of consequence.',
'I must know.',
'Get used to disappointment.',
'Okay.',
'Kill me quickly.',
'I would as soon destroy a stained-glass window as an artist like yourself.',
'However, since I can’t have you following me, either…',
'Please understand, I hold you in the highest respect.',
'Inconceivable!',
'Give her to me.',
'Catch up with us quickly.',
'What do I do?',
'Finish him. Finish him… your way!',
'Oh, good. My way. Thank you, Vizzini.',
'Which one’s my way?',
'Pick up one of those rocks. Get behind the boulder.',
'In a few minutes, the man in black will come running around the bend.',
'The minute his head is in view, hit it with the rock!',
'My way’s not very sportsmanlike.',
'I did that on purpose.',
'I didn’t have to miss.',
'I believe you.',
'So what happens now?',
'We face each other as God intended.',
'Sportsmanlike.',
'No tricks. No weapons.',
'Skill against skill alone.',
'You mean, you’ll put down your rock and I’ll put down my sword, and we’ll try and kill each other like civilized people?',
'I can kill you now.',
'Frankly, I think the odds are slightly in your favor at hand-fighting.',
'It’s not my fault for being the biggest and the strongest.',
'I don’t even exercise.',
'Look, are you just fiddling around with me, or what?',
'I just want you to feel you’re doing well.',
'I hate for people to die embarrassed.',
'You’re quick.',
'And a good thing, too.',
'Why are you wearing a mask?',
'Were you burned by acid or something like that?',
'No, it’s just that they’re terribly comfortable.',
'I think everyone will be wearing them in the future.',
'I just figured why you give me so much trouble.',
'Why’s that, do you think?',
'Well, I haven’t fought just one person… for so long.',
'I’ve been specializing in groups, battling gangs for local charities, that kind of thing.',
'Why should that make such a… difference?',
'Well, you see, you use different moves… when you’re fighting… half a dozen… people… than when you only… have to be worried… about one.',
'I do not envy you the headache you will have when you awake.',
'But in the meantime, rest well… and dream of large women.',
'There was… a mighty duel.',
'It ranged all over.',
'They were both masters.',
'Who won? How did it end?',
'The loser ran off alone, but the winner followed those footprints toward Guilder.',
'Shall we track them both?',
'The loser is nothing. Only the Princess matters.',
'Clearly, this was all planned by warriors of Guilder.',
'We must all be ready for whatever lies ahead.',
'Could this be a trap?',
'I always think everything could be a trap, which is why I’m still alive.',
'So, it is down to you… and it is down to me.',
'If you wish her dead, by all means, keep moving forward.',
'Let me explain.',
'There’s nothing to explain.',
'You’re trying to kidnap what I’ve rightfully stolen.',
'Perhaps an arrangement can be reached?',
'There will be no arrangement, and you’re killing her.',
'Well, if there can be no arrangement, then we are at an impasse.',
'I’m afraid so.',
'I can’t compete with you physically, and you’re no match for my brains.',
'You’re that smart?',
'Let me put it this way.',
'Have you ever heard of Plato, Aristotle, Socrates?',
'Yes.',
'Morons.',
'Really?',
'In that case, I challenge you to a battle of wits.',
'For the Princess?',
'To the death?',
'I accept.',
'Good, then pour the wine.',
'Inhale this, but do not touch.',
'I smell nothing.',
'What you do not smell is called iocane powder.',
'It is odorless, tasteless, dissolves instantly in liquid, and is among the more deadly poisons known to man.',
'All right.',
'Where is the poison?',
'The battle of wits has begun.',
'It ends when you decide, and we both drink… and find out who is right… and who is dead.',
'But it’s so simple.',
'All I have to do is divine from what I know of you.',
'Are you the sort of man who would put the poison into his own goblet or his enemy’s?',
'Now, a clever man would put the poison into his own goblet because he would know that only a great fool would reach for what he was given.',
'I’m not a great fool, so I can clearly not choose the wine in front of you.',
'But you must have known I was not a great fool.',
'You would’ve counted on it, so I can clearly not choose the wine in front of me.',
'You’ve made your decision, then?',
'Not remotely.',
'Because iocane comes from Australia, as everyone knows, and Australia is entirely peopled with criminals, and criminals are used to having people not trust them, as you are not trusted by me, so I can clearly not choose the wine in front of you.',
'Truly, you have a dizzying intellect.',
'Wait till I get going.',
'Where was I?',
'Australia.',
'Yes. Australia.',
'And you must have suspected I would have known the powder’s origin, so I can clearly not choose the wine in front of me.',
'You’re just stalling now.',
'You’d like to think that, wouldn’t you?',
'You’ve beaten my giant, which means you’re exceptionally strong, so you could’ve put the poison in your own goblet, trusting on your strength to save you, so I can clearly not choose the wine in front of you.',
'But you’ve also bested my Spaniard, which means you must’ve studied, and in studying, you must have learned that man is mortal, so you would’ve put the poison as far from yourself as possible, so I can clearly not choose the wine in front of me.',
'You’re trying to trick me into giving away something.',
'It won’t work.',
'It has worked! You’ve given everything away.',
'I know where the poison is.',
'Then make your choice.',
'I will, and I choose…',
'What in the world can that be?',
'What? Where?',
'I don’t see anything.',
'I could’ve sworn I saw something.',
'No matter.',
'What’s so funny?',
'I’ll tell you in a minute.',
'First, let’s drink, me from my glass, and you from yours.',
'You guessed wrong.',
'You only think I guessed wrong.',
'That’s what’s so funny.',
'I switched glasses while your back was turned!',
'You fool!',
'You fell victim to one of the classic blunders.',
'The most famous is never get involved in a land war in Asia, but only slightly less well known is this.',
'Never go in against a Sicilian when death is on the line!',
'Who are you?',
'I’m no one to be trifled with.',
'That is all you ever need know.',
'To think, all that time, it was your cup that was poisoned.',
'They were both poisoned.',
'I spent the last few years building up an immunity to iocane powder.',
'Someone has beaten a giant.',
'There will be great suffering in Guilder if she dies.',
'Catch your breath.',
'If you’ll release me, whatever you ask for ransom, you’ll get it, I promise you.',
'And what is that worth, the promise of a woman?',
'You’re very funny, Highness.',
'I was giving you a chance.',
'It does not matter where you take me.',
'There’s no greater hunter than Prince Humperdinck.',
'He can track a falcon on a cloudy day. He can find you.',
'You think your dearest love will save you?',
'I never said he was my dearest love, and yes, he will save me. That I know.',
'You admit to me you do not love your fiancé?',
'He knows I do not love him.',
'Are not capable of love, is what you mean.',
'I have loved more deeply… than a killer like yourself could ever dream.',
'That was a warning, Highness.',
'The next time, my hand flies on its own, for where I come from, there are penalties when a woman lies.',
'Iocane.',
'I’d bet my life on it.',
'And there are the Princess’s footprints.',
'She is alive, or was, an hour ago.',
'If she is otherwise when I find her, I shall be very put out.',
'Rest, Highness.',
'I know who you are.',
'Your cruelty reveals everything.',
'You’re the Dread Pirate Roberts. Admit it.',
'With pride.',
'What can I do for you?',
'You can die slowly, cut into a thousand pieces.',
'Hardly complimentary, Your Highness.',
'Why loose your venom on me?',
'You killed my love.',
'It’s possible.',
'I kill a lot of people.',
'Who was this love of yours?',
'Another prince like this one?',
'Ugly, rich and scabby?',
'No, a farm boy. Poor.',
'Poor and perfect.',
'With eyes like the sea after a storm.',
'On the high seas your ship attacked, and the Dread Pirate Roberts never takes prisoners.',
'I can’t afford to make exceptions.',
'I mean, once word leaks out that a pirate has gone soft, people begin to disobey you, and then it’s nothing but work, work, work, all the time.',
'You mock my pain!',
'Life is pain, Highness.',
'Anyone who says differently is selling something.',
'I remember this farm boy of yours, I think.',
'This would be what? Five years ago?',
'Does it bother you to hear?',
'Nothing you can say will upset me.',
'He died well. That should please you.',
'No bribe attempts or blubbering.',
'He simply said, “Please. Please, I need to live.”',
'It was the “please” that caught my memory.',
'I asked him what was so important for him.',
'“True love,” he replied.',
'And then he spoke of a girl of surpassing beauty… and faithfulness.',
'I can only assume he meant you.',
'You should bless me for destroying him before he found out what you really are.',
'And what am I?',
'Faithfulness he talked of, madam. Your enduring faithfulness.',
'Now tell me truly. When you found out he was gone, did you get engaged to your prince that same hour, or did you wait a whole week out of respect for the dead?',
'You mocked me once. Never do it again!',
'I died that day!',
'You can die, too, for all I care!',
'As you wish!',
'Oh, my sweet Westley!',
'What have I done?',
'They’ve disappeared.',
'He must have seen us closing in.',
'Which might account for his panicking into error.',
'Unless I’m wrong, and I’m never wrong, they are headed dead into the Fire Swamp.',
'Can you move at all?',
'Move? You’re alive.',
'If you want, I can fly.',
'I told you I would always come for you.',
'Why didn’t you wait for me?',
'Well, you were dead.',
'Death cannot stop true love.',
'All it can do is delay it for a while.',
'I will never doubt again.',
'There will never be a need.',
'Oh, no, no, please.',
'What is it? What’s the matter?',
'They’re kissing again.',
'Do we have to hear the kissing part?',
'Someday, you may not mind so much.',
'Skip on to the Fire Swamp. That sounded good.',
'You’re sick. I’ll humor you.',
'So, now, where were we here?',
'Oh, okay.',
'“Westley and Buttercup raced along the ravine floor.”',
'Your pig fiancé is too late.',
'A few more steps and we’ll be safe in the Fire Swamp.',
'We’ll never survive.',
'Nonsense.',
'You’re only saying that because no one ever has.',
'It’s not that bad.',
'I’m not saying I’d like to build a summer home here, but the trees are actually quite lovely.',
'Well, now, that was an adventure.',
'Singed a bit, were you?',
'You?',
'Well, one thing I will say, the Fire Swamp certainly does keep you on your toes.',
'This will all soon be but a happy memory, because Roberts’ ship, Revenge, is anchored at the far end, and I, as you know, am Roberts.',
'But how is that possible, since he’s been marauding twenty years, and you only left me five years ago?',
'I, myself, am often surprised at life’s little quirks.',
'See, what I told you before about saying “please” was true.',
'It intrigued Roberts, as did my description of your beauty.',
'Finally Roberts decided something. He said:',
'“All right, Westley. I’ve never had a valet. You can try it for tonight. I’ll most likely kill you in the morning.”',
'Three years, he said that.',
'“Good night, Westley. Good work. Sleep well. I’ll most likely kill you in the morning.”',
'It was a fine time for me. I was learning to fence, to fight anything anyone would teach me.',
'And Roberts and I eventually became friends.',
'And then it happened.',
'What? Go on.',
'Well, Roberts had grown so rich, he wanted to retire. So he took me to his cabin, told me a secret.',
'“I am not the Dread Pirate Roberts,” he said.',
'“My name is Ryan.',
'“I inherited the ship from the previous Dread Pirate Roberts, just as you will inherit it from me.',
'“The man I inherited it from was not the real Dread Pirate Roberts either.',
'“His name was Cummerbund.',
'“The real Roberts has been retired fifteen years and living like a king in Patagonia.” (Thank you.)',
'Then he explained the name was the important thing for inspiring the necessary fear.',
'You see, no one would surrender to the Dread Pirate Westley.',
'So, we sailed ashore, took on an entirely new crew, and he stayed aboard for a while, as first mate, all the time calling me Roberts.',
'Once the crew believed, he left the ship, and I have been Roberts ever since.',
'Except, now that we’re together, I shall retire and hand the name over to someone else.',
'Is everything clear to you?',
'We’ll never succeed.',
'We may as well die here.',
'No. No.',
'We have already succeeded.',
'I mean, what are the three terrors of the Fire Swamp?',
'One, the flame spurt. No problem.',
'There’s a popping sound preceding each. We can avoid that.',
'Two, the lightning sand, but you were clever enough to discover what that looks like, so in the future, we can avoid that, too.',
'Westley, what about the R.O.U.S.s?',
'Rodents Of Unusual Size?',
'I don’t think they exist.',
'Westley!',
'We did it.',
'Now, was that so terrible?',
'Surrender.',
'You mean, you wish to surrender to me?',
'Very well. I accept.',
'I give you full marks for bravery.',
'Don’t make yourself a fool.',
'But how will you capture us?',
'We know the secrets of the Fire Swamp.',
'We can live there quite happily for some time, so whenever you feel like dying, feel free to visit.',
'I tell you once again, surrender!',
'It will not happen.',
'For the last time, surrender!',
'Death first!!',
'Will you promise not to hurt him?!',
'What was that?',
'What was that??',
'If we surrender, and I return with you, will you promise not to hurt this man?',
'May I live a thousand years and never hunt again.',
'He is a sailor on the pirate ship Revenge.',
'Promise to return him to his ship.',
'I swear it will be done!',
'Once we are out of sight, take him back to Florin and throw him in the Pit of Despair.',
'I swear it will be done.',
'I thought you were dead once, and it almost destroyed me.',
'I could not bear it if you died again, not when I could save you.',
'Come, sir.',
'We must get you to your ship.',
'We are men of action. Lies do not become us.',
'Well spoken, sir.',
'What is it?',
'You have six fingers on your right hand.',
'Someone was looking for you.',
'Where am I?',
'The Pit of Despair.',
'Don’t even think—!',
'Don’t even think about trying to escape.',
'The chains are far too thick.',
'And don’t dream of being rescued either.',
'The only way in is secret.',
'Only the Prince, the Count and I know how to get in and out.',
'Then I’m here till I die?',
'Till they kill you, yeah.',
'Then why bother curing me?',
'The Prince and the Count always insist on everyone being healthy before they’re broken.',
'So, it’s to be torture?',
'I can cope with torture.',
'You don’t believe me?',
'You survived the Fire Swamp. You must be very brave.',
'But nobody withstands the machine.',
'She’s been like that ever since the Fire Swamp.',
'It’s my father’s failing health that’s upsetting her.',
'Of course.',
'“The King died that very night, and before the following dawn, Buttercup and Humperdinck were married.',
'“And at noon, she met her subjects again, this time as their queen.”',
'My father’s final words were—',
'Hold it. Hold it, Grandpa.',
'You read that wrong. She doesn’t marry Humperdinck.',
'She marries Westley. I’m just sure of it.',
'After all that Westley did for her, if she didn’t marry him, it wouldn’t be fair.',
'Well, who says life is fair?',
'Where is that written? Life isn’t always fair.',
'I’m telling you, you’re messing up the story.',
'Now, get it right!',
'Do you want me to go on with this?',
'Yes.',
'All right then.',
'No more interruptions.',
'“At noon, she met her subjects again, this time as their queen.”',
'My father’s final words were, “Love her as I loved her, and there will be joy.”',
'I present to you your queen, Queen… Buttercup.',
'Boo! Boo! Boo!',
'Why do you do this?',
'Because you had love in your hands and you gave it up!',
'But they would’ve killed Westley if I hadn’t done it.',
'Your true love lives, and you marry another!',
'True love saved her in the Fire Swamp and she treated it like garbage.',
'And that’s what she is, the queen of refuse!',
'So bow down to her if you want, bow to her.',
'Bow to the queen of slime, the queen of filth, the queen of putrescence!',
'Boo! Boo!',
'Rubbish! Filth! Slime! Muck!',
'Boo! Boo! Boo!!',
'“It was ten days till the wedding.',
'“The King still lived, but Buttercup’s nightmares were growing steadily worse.”',
'See? Didn’t I tell you she’d never marry that rotten Humperdinck?',
'Yes, you’re very smart. Shut up.',
'It comes to this.',
'I love Westley. I always have.',
'I know now, I always will.',
'If you tell me I must marry you in ten days, please believe I will be dead by morning.',
'I could never cause you grief.',
'Consider our wedding off.',
'You, uh, returned this Westley to his ship?',
'Yes.',
'Then we will simply alert him.',
'Beloved, are you certain he still wants you?',
'After all, it was you who did the leaving in the Fire Swamp.',
'Not to mention that pirates are not known to be men of their words.',
'My Westley will always come for me.',
'I suggest a deal.',
'You write four copies of a letter.',
'I’ll send my four fastest ships, one in each direction.',
'The Dread Pirate Roberts is always close to Florin this time of year.',
'We’ll run up the white flag and deliver your message.',
'If Westley wants you, bless you both.',
'If not, please consider me as an alternative to suicide.',
'Are we agreed?',
'Your princess is really quite a winning creature.',
'A trifle simple, perhaps, but her appeal is undeniable.',
'I know. The people are quite taken with her.',
'It’s odd, but when I hired Vizzini to have her murdered on our engagement day, I thought that was clever.',
'But it’s going to be so much more moving when I strangle her on our wedding night.',
'Once Guilder is blamed, the nation will be truly outraged.',
'They’ll demand we go to war.',
'Now, where is that secret knot?',
'It’s impossible to find.',
'Are you coming down into the pit?',
'Westley’s got his strength back.',
'I’m starting him on the machine tonight.',
'Tyrone, you know how much I love watching you work.',
'But I’ve got my country’s five hundredth anniversary to plan, my wedding to arrange, my wife to murder, and Guilder to frame for it. I’m swamped.',
'Get some rest.',
'If you haven’t got your health, you haven’t got anything.',
'Beautiful, isn’t it?',
'Took me half a lifetime to invent it.',
'I’m sure you’ve discovered my deep and abiding interest in pain.',
'At present, I’m writing the definitive work on the subject.',
'So, I want you to be totally honest with me on how the machine makes you feel.',
'This being our first try, I’ll use the lowest setting.',
'As you know, the concept of the suction pump is centuries old.',
'Really, that’s all this is, except that instead of sucking water, I’m sucking life.',
'I’ve just sucked one year of your life away.',
'I might one day go as high as five, but I really don’t know what that would do to you.',
'So, let’s just start with what we have.',
'What did this do to you? Tell me.',
'And remember, this is for posterity, so be honest.',
'How do you feel?',
'Interesting.',
'Yellin.',
'Sire.',
'As Chief Enforcer of all Florin, I trust you with this secret.',
'Killers from Guilder are infiltrating the Thieves’ Forest and plan to murder my bride on our wedding night.',
'My spy network has heard no such news.',
'Any word from Westley?',
'Too soon, my angel.',
'Patience.',
'He will come for me.',
'Of course.',
'She will not be murdered!',
'On the day of the wedding, I want the Thieves’ Forest emptied, and every inhabitant arrested.',
'Many of the thieves will resist.',
'My regular enforcers will be inadequate.',
'Form a Brute Squad, then!',
'I want the Thieves’ Forest emptied before I wed.',
'It won’t be easy, sire.',
'Try ruling the world sometime.',
'“The day of the wedding arrived.',
'“The Brute Squad had their hands full carrying out Humperdinck’s orders.”',
'Is everybody out?',
'Almost.',
'There’s a Spaniard giving us some trouble.',
'Well, you give him some trouble.',
'Move.',
'I am waiting for you, Vizzini.',
'You told me to go back to the beginning, so I have.',
'This is where I am… and this is where I’ll stay.',
'I will not be moved.',
'Ho, there!',
'I do not budge. Keep your “Ho, there.”',
'But the Prince gave orders.',
'So did Vizzini.',
'When a job went wrong, you went back to the beginning.',
'Well, this is wherewe got the job, so it’s the beginning.',
'And I am staying till Vizzini comes.',
'You, Brute, come here!',
'I am waiting… for Vizzini.',
'You surely are a meanie.',
'Hello.',
'It’s you.',
'True.',
'You don’t look so good.',
'You don’t smell so good either.',
'Perhaps not. I feel fine.',
'“Fezzik and Inigo were reunited.',
'“And as Fezzik nursed his inebriated friend back to health, he told Inigo of Vizzini’s death and the existence of Count Rugen, the six-fingered man.',
'“Considering Inigo’s life-long search, he handled the news surprisingly well.',
'“Fezzik took great care in reviving Inigo.”',
'That’s enough! That’s enough!',
'Where is this Rugen now, so I may kill him?',
'He’s with the Prince in the castle.',
'But the castle gate is guarded by thirty men.',
'How many could you handle?',
'I don’t think more than ten.',
'Leaving twenty for me.',
'At my best, I could never defeat that many.',
'I need Vizzini to plan. I have no gift for strategy.',
'But Vizzini is dead.',
'No. Not Vizzini.',
'I need the man in black.',
'What?',
'Look. He bested you with strength, your greatness.',
'He bested me with steel.',
'He must have out thought Vizzini.',
'And a man who can do that can plan my castle onslaught any day.',
'Let’s go.',
'Where?',
'Find the man in black, obviously.',
'But you don’t know where he is.',
'Don’t bother me with trifles.',
'After twenty years, at last my father’s soul will be at peace.',
'There will be blood tonight!',
'Rise and report.',
'The Thieves’ Forest is emptied.',
'Thirty men guard the castle gate.',
'Double it. My princess must be safe.',
'The gate has but one key.',
'And I carry that.',
'My dulcet darling.',
'Tonight, we marry.',
'Tomorrow morning, your men will escort us to Florin Channel, where every ship in my armada waits to accompany us on our honeymoon.',
'Every ship but your four fastest, you mean.',
'Every ship but the four you sent.',
'Yes. Yes, of course. Naturally, not those four.',
'Your Majesty.',
'You never sent the ships.',
'Don’t bother lying.',
'It doesn’t matter. Westley will come for me anyway.',
'You’re a silly girl.',
'Yes, I am a silly girl, for not having seen sooner that you are nothing but a coward with a heart full of fear.',
'I would not say such things if I were you.',
'Why not? You can’t hurt me.',
'Westley and I are joined by the bonds of love.',
'And you cannot track that, not with a thousand bloodhounds.',
'And you cannot break it, not with a thousand swords.',
'And when I say you’re a coward, that is only because you are the slimiest weakling… ever to crawl the earth!',
'I would not say such things if I were you!',
'You truly love each other, and so you might have been truly happy.',
'Not one couple in a century has that chance, no matter what the storybooks say.',
'And so, I think no man in a century will suffer as greatly as you will.',
'Not to fifty!',
'Fezzik. Fezzik, listen.',
'Do you hear?',
'That is the sound of ultimate suffering.',
'My heart made that sound when Rugen slaughtered my father.',
'The man in black makes it now.',
'The man in black?',
'His true love is marrying another tonight, so who else has the cause for ultimate suffering?',
'Excuse me. Pardon me, it’s important.',
'Fezzik, please.',
'Everybody, move!',
'Thank you.',
'Where is the man in black?',
'You get there from this grove, yes?',
'Fezzik, jog his memory.',
'I’m sorry, Inigo. I didn’t meant to jog him so hard.',
'Inigo?',
'Father, I have failed you for twenty years.',
'Now, our misery can end.',
'Somewhere… Somewhere close by is a man who can help us.',
'I cannot find him alone. I need you.',
'I need you to guide my sword.',
'Please.',
'Guide my sword.',
'He’s dead.',
'Just is not fair.',
'Grandpa, Grandpa, wait. Wait.',
'What did Fezzik mean, “He’s dead”?',
'I mean, he didn’t mean “dead”.',
'Westley’s only faking, right?',
'You want me to read this or not?',
'Who gets Humperdinck?',
'I don’t understand.',
'Who kills Prince Humperdinck?',
'At the end? Somebody’s gotta do it.',
'Is it Inigo? Who?',
'Nobody. Nobody kills him.',
'He lives.',
'You mean, he wins?',
'Jesus, Grandpa, what did you read me this thing for?',
'You know, you’ve been very sick and you’re taking this story very seriously.',
'I think we ought to stop now.',
'No, I’m okay. I’m okay.',
'Sit down. I’m all right.',
'Okay.',
'All right, now, let’s see. Where were we?',
'Oh, yes.',
'In the Pit of Despair.',
'Well… The Montoyas have never taken defeat easily.',
'Come along, Fezzik. Bring the body.',
'The body?',
'Have you any money?',
'I have a little.',
'I just hope it’s enough to buy a miracle, that’s all.',
'Go away!',
'What? What?',
'Are you the Miracle Max who worked for the King all those years?',
'The King’s stinking son fired me, and thank you so much for bringing up such a painful subject.',
'While you’re at it, why don’t you give me a nice paper cut and pour lemon juice on it?',
'We’re closed!',
'Beat it, or I’ll call the Brute Squad.',
'I’m on the Brute Squad.',
'You are the Brute Squad.',
'We need a miracle. It’s very important.',
'Look, I’m retired. And besides, why would you want someone the King’s stinking son fired?',
'I might kill whoever you wanted me to miracle.',
'He’s already dead.',
'He is, huh?',
'I’ll take a look. Bring him in.',
'I’ve seen worse.',
'Sir? Sir?',
'We’re in a terrible rush.',
'Don’t rush me, sonny.',
'You rush a miracle man, you get rotten miracles.',
'You got money?',
'Sixty-five.',
'I never worked for so little, except once, and that was a very noble cause.',
'This is noble, sir.',
'His wife is crippled.',
'His children are on the brink of starvation.',
'Are you a rotten liar.',
'I need him to help avenge my father, murdered these twenty years.',
'Your first story was better. Where’s that bellows cranny?',
'He probably owes you money, huh?',
'Well, I’ll ask him.',
'He’s dead. He can’t talk.',
'Look who knows so much.',
'Well, it just so happens that your friend here is only mostly dead.',
'There’s a big difference between mostly dead and all dead.',
'Please, open his mouth.',
'Now, mostly dead is slightly alive.',
'Now, all dead… Well, with all dead, there’s usually only one thing that you can do.',
'What’s that?',
'Go through his clothes and look for loose change.',
'Hey!',
'Hello in there! Hey!',
'What’s so important?',
'What you got here that’s worth living for?',
'True love.',
'True love. You heard him.',
'You could not ask for a more noble cause than that.',
'Sonny, true love is the greatest thing in the world, except for a nice M.L.T.',
'A mutton, lettuce and tomato sandwich when the mutton is nice and lean… and the tomato is ripe.',
'They’re so perky. I love that.',
'But that’s not what he said.',
'He distinctly said, “To blave.”',
'And as we all know, “to blave” means “to bluff”.',
'So you’re probably playing cards and he cheated—',
'Liar! Liar!',
'Liar!',
'Get back, witch!',
'I’m not a witch, I’m your wife!',
'But after what you just said, I’m not even sure I want to be that anymore.',
'You never had it so good.',
'“True love.” He said “true love,” Max.',
'Don’t say another word, Valerie.',
'He’s afraid.',
'Ever since Prince Humperdinck fired him, his confidence is shattered.',
'Why’d you say that name?',
'You promised me that you’d never say that name!',
'What, “Humperdinck”?',
'Aah!',
'Humperdinck! Humperdinck! Humperdinck!',
'Humperdi-i-inck! Humperdinck! Humperdinck! Humperdinck! Humperdinck!',
'I’m not listening!',
'True love lies expiring, and you don’t have the decency to say why you won’t help.',
'Nobody’s hearing nothin’.',
'Humperdinck! Humperdinck!',
'This is Buttercup’s true love.',
'Humperdinck! Humperdinck! Humperdinck! Humperdinck! Humperdinck! Humperdinck! Humperdinck! Humperdinck!',
'If you heal him, he will stop Humperdinck’s wedding.',
'Wait, wait.',
'I make him better, Humperdinck suffers?',
'Humiliations galore.',
'Ha ha ha! Hide a little Danish!',
'That is a noble cause.',
'Give me the sixty-five. I’m on the job.',
'Hah-woo!',
'That’s a miracle pill?',
'The chocolate coating makes it go down easier.',
'But you have to wait fifteen minutes for full potency.',
'And you shouldn’t go in swimming after for at least, what?',
'An hour.',
'Yeah, an hour.',
'A good hour.',
'Thank you for everything.',
'Okay.',
'Bye-bye, boys.',
'Have fun storming the castle.',
'Think it’ll work?',
'It would take a miracle.',
'Bye-bye!',
'Bye!',
'Inigo, there’s more than thirty.',
'What’s the difference?',
'We’ve got him. Help me here.',
'We’ll have to force-feed him.',
'Has it been fifteen minutes?',
'We can’t wait.',
'The wedding’s in half an hour.',
'We must strike in the hustle and the bustle beforehand.',
'Tilt his head back.',
'Open his mouth.',
'How long do we have to wait before if we know the miracle works?',
'Your guess is as good as mine.',
'I’ll beat you at your part. I’ll take you both together!',
'I guess not very long.',
'Why won’t my arms move?',
'You’ve been mostly dead all day.',
'We had Miracle Max make a pill to bring you back.',
'Who are you? Are we enemies?',
'Why am I on this wall? Where is Buttercup?',
'Let me explain.',
'No, there is too much. Let me sum up.',
'Buttercup is marrying Humperdinck in a little less than half an hour, so all we have to do is get in, break up the wedding, steal the princess, make our escape.',
'After I kill Count Rugen.',
'That doesn’t leave much time for dilly-dallying.',
'You just wiggled your finger. That’s wonderful.',
'I’ve always been a quick healer. What are our liabilities?',
'There is but one working castle gate.',
'Come on.',
'And it is guarded by… sixty men.',
'And our assets?',
'Your brains, Fezzik’s strength, my steel.',
'That’s it?',
'Impossible.',
'If I had a month to plan, maybe I could come up with something, but this—',
'You just shook your head. That doesn’t make you happy?',
'My brains, his steel and your strength against sixty men, and you think a little head jiggle is supposed to make me happy?',
'If we only had a wheelbarrow, that would be something.',
'Where did we put the wheelbarrow the albino had?',
'Over the albino, I think.',
'Why didn’t you list that among our assets in the first place?',
'What I wouldn’t give for a holocaust cloak.',
'There, we cannot help you.',
'Will this do?',
'Where did you get that?',
'At Miracle Max’s.',
'It fit so nice, he said I could keep it.',
'All right, all right. Come on. Help me up.',
'Now, I’ll need a sword, eventually.',
'Why?',
'You can’t even lift one.',
'True, but that’s hardly common knowledge, is it?',
'Thank you. Now, there may be problems once we’re inside.',
'I’ll say. How do I find the Count?',
'Once I do, how do I find you again?',
'Once I find you again, how do we escape?',
'Don’t pester him. He’s had a hard day.',
'Right. Right. Sorry.',
'Inigo.',
'What?',
'I hope we win.',
'You don’t seem excited, my little muffin.',
'Should I be?',
'Brides often are, I’m told.',
'I do not marry tonight.',
'My Westley will save me.',
'Marriage.',
'Marriage is what brings us together today.',
'Marriage, that blessed arrangement, that dream within a dream.',
'Stand your ground, men! Stand your ground!',
'Stand your ground!',
'I am the Dread Pirate Roberts!',
'There will be no survivors!',
'Now?',
'Not yet.',
'My men are here, I am here. But soon you will not be here.',
'Now?!',
'Light him.',
'The Dread Pirate Roberts… takes no survivors.',
'All your worst nightmares… are about to come true!',
'Then love, true love, will follow you… forever.',
'The Dread Pirate Roberts… is here for your souls!',
'Stay where you are! Stand and fight.',
'Stay where you are!',
'So treasure your love—',
'Skip to the end.',
'Have you the ring?',
'Here comes my Westley now.',
'Fezzik, the portcullis!',
'Your Westley is dead.',
'I killed him myself.',
'Then why is there fear behind your eyes?',
'Give us the gate key.',
'I have no gate key.',
'Fezzik, tear his arms off.',
'Oh, you mean this gate key.',
'And do you, Princess Buttercup—',
'Man and wife! Say, “Man and wife”!',
'Man and wife.',
'Escort the bride to the honeymoon suite. I’ll be there shortly.',
'He didn’t come.',
'Kill the dark one and the giant, but leave the third for questioning.',
'Hello. My name is Inigo Montoya.',
'You killed my father. Prepare to die.',
'Fezzik! I need you!',
'I can’t leave him alone.',
'He’s getting away from me, Fezzik! Please!',
'Fezzik!',
'I’ll be right back.',
'Thank you.',
'Strange wedding.',
'Yes, a very strange wedding.',
'Come along.',
'What was that for?',
'Because you’ve always been so kind to me.',
'And I won’t be seeing you again, since I’m killing myself once we reach the honeymoon suite.',
'Won’t that be nice, hmm?',
'She kissed me!',
'Sorry, Father… I tried… I tried.',
'You must be that little Spanish brat',
'I taught a lesson to all those years ago.',
'Simply incredible.',
'Have you been chasing me your whole life, only to fail now?',
'I think that’s the worst thing I’ve ever heard.',
'How marvelous.',
'There’s a shortage of perfect breasts in this world.',
'It would be a pity to damage yours.',
'Westley! Oh, Westley, darling!',
'Westley, why won’t you hold me?',
'Gently.',
'At a time like this?',
'That’s all you can think to say? “Gently”?',
'Gently!',
'Good heavens. Are you still trying to win?',
'You’ve got an overdeveloped sense of vengeance.',
'It’s going to get you into trouble someday.',
'Hello… My name is Inigo Montoya. You killed my father. Prepare to die.',
'Hello. My name is Inigo Montoya. You killed my father. Prepare to die.',
'Hello! My name is Inigo Montoya. You killed my father. Prepare to die.',
'Stop saying that!',
'Hello! My name is Inigo Montoya! You killed my father! Prepare to die!',
'No!',
'Offer me money.',
'Yes.',
'Power, too. Promise me that.',
'All that I have and more. Please.',
'Offer me everything I ask for.',
'Anything you want.',
'I want my father back, you son of a bitch.',
'Westley, will you ever forgive me?',
'What hideous sin have you committed lately?',
'I got married. I didn’t want to. It all happened so fast.',
'Never happened.',
'What?',
'It never happened.',
'But it did. I was there.',
'This old man said, “Man and wife.”',
'Did you say, “I do”?',
'No. We sort of skipped that part.',
'Then you’re not married.',
'If you didn’t say it, you didn’t do it.',
'Wouldn’t you agree, Your Highness?',
'A technicality that will shortly be remedied.',
'But first things first.',
'To the death.',
'No!',
'To the pain.',
'I don’t think I’m quite familiar with that phrase.',
'I’ll explain.',
'And I’ll use small words, so that you’ll be sure to understand, you warthog-faced buffoon.',
'That may be the first time in my life a man has dared insult me.',
'It won’t be the last.',
'“To the pain” means the first thing you lose will be your feet, below the ankles.',
'Then your hands at the wrists.',
'Next, your nose.',
'And then my tongue, I suppose?',
'I killed you too quickly the last time, a mistake I don’t mean to duplicate tonight.',
'I wasn’t finished!',
'The next thing you lose will be your left eye, followed by your right.',
'And then my ears. I understand. Let’s get on with it.',
'Wrong! Your ears you keep, and I’ll tell you why.',
'So that every shriek of every child at seeing your hideousness will be yours to cherish.',
'Every babe that weeps at your approach, every woman who cries out, “Dear, God, what is that thing?” will echo in your perfect ears.',
'That is what “to the pain” means.',
'It means I leave you in anguish, wallowing in freakish misery forever.',
'I think you’re bluffing.',
'It’s possible, pig.',
'I might be bluffing.',
'It’s conceivable, you miserable, vomitous mass, that I’m only lying here because I lack the strength to stand.',
'Then again, perhaps I have the strength after all.',
'Drop your sword.',
'Have a seat.',
'Tie him up.',
'Make it as tight as you like.',
'Where’s Fezzik?',
'I thought he was with you.',
'No.',
'In that case…',
'Help him.',
'Why does Westley need helping?',
'Because he has no strength.',
'I knew it. I knew you were bluffing!',
'I knew he was bluffing.',
'Shall I dispatch him for you?',
'Thank you, but no. Whatever happens to us, I want him to live a long life, alone with his cowardice.',
'Inigo!',
'Inigo, where are you?',
'Oh, now, there you are.',
'Inigo, I saw the prince’s stables.',
'And there they were. Four white horses.',
'And I thought, “There are four of us, if we ever find the lady.”',
'Hello, lady.',
'So I took them with me, in case we ever bumped into each other.',
'I guess we just did.',
'Fezzik, you did something right.',
'Don’t worry, I won’t let it go to my head.',
'You know, it’s very strange.',
'I have been in the revenge business so long, now that it’s over, I don’t know what to do with the rest of my life.',
'Have you ever considered piracy?',
'You’d make a wonderful Dread Pirate Roberts.',
'“They rode to freedom.',
'“And as dawn arose, “Westley and Buttercup knew they were safe.',
'“A wave of love swept over them, “and as they reached for each other…”',
'What? What?',
'No, it’s kissing again. You don’t want to hear that.',
'I… I don’t mind so much.',
'Okay.',
'“Since the invention of the kiss, there have been five kisses that were rated the most passionate, the most pure.',
'“This one left them all behind.',
'“The end.”',
'Now, I think you ought to go to sleep.',
'Okay…',
'Okay… Okay… Okay… All right…',
'So long.',
'Grandpa?',
'Maybe you could come over and read it again to me tomorrow.',
'As you wish.',
'Screenplay by WILLIAM GOLDMAN\nBased upon his book',
];
