module.exports = {
    alice: 'Alice_LBL',
    barsoom: 'Barsoom_LBL',
    bartleby: 'Bartleby_LBL',
    bttf: 'BTTF_LBL',
    ferris: 'Ferris_LBL',
    ghostbusters: 'Ghostbuster_LBL',
    hobbit: 'Hobbit_LBL',
    indyjones: 'IndyJones_LBL',
    lotr: 'LOTR_LBL',
    midsummer: 'Midsummer_LBL',
    mobydick: 'MobyDick_LBL',
    princessbride: 'ThePrincess_LBL',
    romeojuliet: 'RomeoJuliet_LBL',
    starwars: 'StarWars_LBL',
    test: 'Tweets_LBL',
    timemachine: 'TimeMachine_LBL',
    walden: 'Walden_LBL',
    willows: 'Willows_LBL',
};
